(function () {
  "use strict";

  const PAPER_URL = "https://arxiv.org/pdf/2404.06004v2";
  const PAPER_ABSTRACT_URL = "https://arxiv.org/abs/2404.06004";

  const paperSource = (label, page) => ({
    label,
    url: `${PAPER_URL}#page=${page}`,
  });

  const traceEvent = (id, at, lane, label, source, destination, payload, direction, factStatus = "paper-backed") => ({
    id,
    at,
    lane,
    label,
    source,
    destination,
    payload,
    direction,
    factStatus,
  });

  const phaseTrace = (sceneFamily, stateLabel, events) => ({
    sceneFamily,
    stateLabel,
    events,
  });

  window.AISAQ_CONTENT = Object.freeze({
    schemaVersion: 2,

    traceContract: {
      time: "Every event.at is normalized to its phase: 0 is phase start and 1 is phase end.",
      ordering: "Events are listed in deterministic playback order; equal timestamps are intentionally avoided.",
      sceneFamilies: ["layout", "host", "read", "score", "commit", "pack", "evidence"],
      directions: ["stationary", "down", "up", "lateral", "in", "out", "release"],
      lanes: ["shared", "diskann", "aisaq"],
      factStatuses: ["paper-backed", "derived", "illustrative"],
      addressPolicy: "Node addresses are symbolic, such as LBA(p). Numeric LBAs and request identifiers are not invented.",
      retentionPolicy: "Candidate list L stores node ID, scalar PQ distance, and expansion state. A separate seen-ID set deduplicates insertions. The historical authors' implementation writes ID plus scalar exact distance to full_retset during expansion; paper V is the logical reranking set, not the C++ seen set.",
    },

    meta: {
      id: "aisaq-visual-guide",
      title: "AiSAQ, one graph hop at a time",
      shortTitle: "Inside AiSAQ",
      subtitle: "See how prebuilding neighbor PQ codes into SSD node chunks changes memory, I/O, and index switching.",
      paperTitle: "AiSAQ: All-in-Storage ANNS with Product Quantization for DRAM-free Information Retrieval",
      paperVersion: "arXiv:2404.06004v2, 26 February 2025",
      authors: [
        "Kento Tatsuno",
        "Daisuke Miyashita",
        "Taiga Ikeda",
        "Kiyoshi Ishiyama",
        "Kazunari Sumiyoshi",
        "Jun Deguchi",
      ],
      paperUrl: PAPER_URL,
      abstractUrl: PAPER_ABSTRACT_URL,
      estimatedMinutes: 9,
      stageDurationUnit: "seconds",
      traceScope: {
        primaryModel: "The paper v2 evaluated full-inline AiSAQ layout: every outneighbor PQ code is stored in the current node's SSD chunk.",
        queryPath: "The animated transport path is a node-cache miss. An aligned logical request travels toward SSD and one or more 4 KiB units return into a reusable DRAM scratch buffer.",
        cacheDisclosure: "A node-cache hit bypasses the SSD request and return shown here; it is disclosed but not mixed into the miss trace.",
        repositoryDisclosure: "The current authors' repository also supports partial or on-demand inline PQ placement, vector rearrangement, multiple entrypoints, vector beamwidth, and static or dynamic PQ caches. Those post-paper extensions are outside this visual's primary trace.",
        queryResidency: "The query q and common centroid/LUT state remain host-side; the animation never sends q to SSD.",
      },
      learningOutcomes: [
        "Explain which data DiskANN keeps in DRAM and which data it reads from SSD.",
        "Trace one search hop in DiskANN and AiSAQ.",
        "Explain why AiSAQ memory does not grow with the number of indexed vectors in the same way.",
        "Name the SSD-size, I/O, feature, and evaluation caveats behind the headline result.",
      ],
    },

    sources: {
      paper: {
        label: "Primary source: AiSAQ paper, arXiv:2404.06004v2",
        url: PAPER_URL,
      },
      abstract: {
        label: "AiSAQ abstract and version history on arXiv",
        url: PAPER_ABSTRACT_URL,
      },
      learningMethod: {
        label: "Method reference: How I use LLMs to learn complex topics",
        url: "https://laurentiugabriel.github.io/blog/articles/how-i-use-llms-to-learn/",
      },
      implementation: {
        label: "Authors' AiSAQ DiskANN implementation",
        url: "https://github.com/kioxia-jp/aisaq-diskann",
      },
    },

    learningMethod: {
      sourceLabel: "Inspired by Laurentiu Raducu's simulation-based learning workflow",
      sourceUrl: "https://laurentiugabriel.github.io/blog/articles/how-i-use-llms-to-learn/",
      adaptations: [
        "Map abstract concepts to persistent objects: graph nodes, a query marker, DRAM shelves, SSD chunks, and 4 KB blocks.",
        "Let the learner pause, replay, and compare the same graph hop under two data placements.",
        "Follow the walkthrough with retrieval questions instead of relying on rereading alone.",
      ],
    },

    stages: [
      {
        id: "layout-at-rest",
        number: 1,
        navLabel: "Layout at rest",
        short: "Where the bytes live",
        title: "Same graph, different address for the next comparison",
        body: "Before a query begins, DiskANN and AiSAQ hold the same graph topology and full vectors. The defining change is where each node's PQ code is laid out: one dataset-wide DRAM array in DiskANN, or repeated beside incoming references inside prebuilt AiSAQ SSD chunks.",
        summary: "No PQ bytes migrate at query time: this compares two indices as already built. DiskANN keeps all N PQ codes in DRAM; AiSAQ prebuilds neighbor PQ codes into SSD node chunks.",
        sourceLabel: "Paper §2.3–§3.1 and Figure 2 — data placement",
        sourceUrl: `${PAPER_URL}#page=4`,
        duration: 16,
        focus: "overview",
        learningGoal: "Identify the one placement change while holding graph topology and vector roles constant.",
        checkpoint: {
          prompt: "Pause: is AiSAQ moving PQ codes from DRAM to SSD while a query runs?",
          reveal: "No. The animation compares two already-built layouts. AiSAQ's index creator has stored each outneighbor's PQ code inside the current node's SSD chunk before search begins.",
          confusionHint: "Read the two observatory lanes as alternative index layouts at rest, not as a before-and-after migration.",
        },
        citations: [
          paperSource("§2.3 DiskANN node chunks", 2),
          paperSource("§2.4 Drawbacks and §3.1 Methodology", 3),
          paperSource("Figure 2 — DiskANN and AiSAQ data placement", 4),
        ],
        phases: [
          {
            id: "same-graph",
            label: "Hold the graph constant",
            shared: "Both indices use the same Vamana directed graph: the same nodes, edges, entrypoint, and query objective.",
            diskann: "DiskANN will traverse this graph with PQ distances and compute one exact full-vector distance as each node is expanded.",
            aisaq: "AiSAQ will traverse the same graph with the same two distance roles and the same exact-score commitment.",
            difference: "No algorithmic difference yet. The logical graph is held constant, and both observatory lanes illuminate the same illustrative node-and-edge pattern.",
            cue: "align-graphs",
            trace: phaseTrace("layout", "SAME GRAPH · TWO BYTE ADDRESSES", [
              traceEvent("graph-fixed", 0, "shared", "Hold topology fixed", "index.graph", "diskann.graph + aisaq.graph", "same nodes, directed edges, entrypoint, and search objective", "stationary"),
              traceEvent("roles-fixed", 0.45, "shared", "Hold scoring roles fixed", "search.contract", "diskann.cpu + aisaq.cpu", "PQ distance steers traversal; exact full-vector distance verifies an expanded node", "lateral"),
              traceEvent("route-highlight", 0.76, "shared", "Highlight one teaching route", "graph.entrypoint", "graph.node(p)", "illustrative visit path only", "out", "illustrative"),
            ]),
          },
          {
            id: "common-ssd-records",
            label: "Inspect the SSD records",
            shared: "Every node chunk contains the current node's full-precision vector, its outdegree, and its outneighbor IDs.",
            diskann: "Its SSD chunk ends after the neighbor IDs; neighbor PQ codes are not stored in that chunk.",
            aisaq: "Its SSD chunk continues with the PQ code corresponding to every outneighbor ID.",
            difference: "AiSAQ's prebuilt node chunk is larger because the neighbor codes travel with the IDs that reference them.",
            cue: "open-node-chunks",
            trace: phaseTrace("layout", "OPEN PREBUILT NODE p", [
              traceEvent("diskann-record", 0, "diskann", "Expose DiskANN record", "diskann.index-builder", "diskann.ssd.LBA(p)", "full vector(p) + outdegree + outneighbor IDs", "in"),
              traceEvent("aisaq-record", 0.4, "aisaq", "Expose AiSAQ full-inline record", "aisaq.index-builder", "aisaq.ssd.LBA(p)", "full vector(p) + outdegree + outneighbor IDs + each outneighbor PQ code", "in"),
              traceEvent("ssd-copies-stable", 0.78, "shared", "Freeze stored copies", "diskann.ssd.LBA(p) + aisaq.ssd.LBA(p)", "storage.at-rest", "prebuilt node records; unchanged by a query", "stationary"),
            ]),
          },
          {
            id: "pq-residency",
            label: "Compare DRAM residency",
            shared: "Both need PQ codes to estimate query-to-neighbor distance during graph navigation.",
            diskann: "A dataset-wide array of all N node PQ codes is resident in DRAM before search.",
            aisaq: "The all-N array is absent; entrypoint code state and hop-local codes account for the PQ working set.",
            difference: "DiskANN's PQ residency scales with N; the paper bounds AiSAQ's simultaneous PQ-code working set by R + n_ep, not its total process memory.",
            cue: "compare-dram-shelves",
            trace: phaseTrace("layout", "COMPARE PQ RESIDENCY", [
              traceEvent("diskann-pq-resident", 0, "diskann", "Load global PQ state", "diskann.index.pq-file", "diskann.dram.pq-array", "all N node PQ codes", "up"),
              traceEvent("aisaq-pq-inline", 0.38, "aisaq", "Keep neighbor PQ inline", "aisaq.ssd.LBA(p)", "aisaq.ssd.LBA(p)", "outneighbor PQ codes duplicated in prebuilt chunks", "stationary"),
              traceEvent("aisaq-entrypoint-state", 0.72, "aisaq", "Keep seed code ready", "aisaq.index.metadata", "aisaq.dram.entrypoint", "n_ep entrypoint PQ code(s)", "up"),
            ]),
          },
          {
            id: "prebuilt-not-transfer",
            label: "Lock in the mental model",
            shared: "Each side is ready to receive the same query; neither graph is being rebuilt in the search animation.",
            diskann: "Its PQ array was loaded into DRAM as index-search state.",
            aisaq: "Its duplicated neighbor PQ codes were written into the index file during index creation.",
            difference: "This is a storage-layout comparison, not a runtime scene of codes being moved from one side to the other.",
            cue: "freeze-layouts",
            trace: phaseTrace("layout", "INDEX COPIES DO NOT MIGRATE", [
              traceEvent("diskann-ready", 0, "diskann", "DiskANN ready", "diskann.dram.pq-array + diskann.ssd.index", "diskann.search", "preloaded global PQ array plus SSD node chunks", "stationary"),
              traceEvent("aisaq-ready", 0.34, "aisaq", "AiSAQ ready", "aisaq.ssd.full-inline-index", "aisaq.search", "prebuilt full-inline SSD node chunks", "stationary"),
              traceEvent("query-waits-host", 0.7, "shared", "Keep q outside storage", "host.query", "host.query", "q (read-only; remains host-side)", "stationary"),
            ]),
          },
        ],
      },
      {
        id: "entrypoint",
        number: 2,
        navLabel: "Enter the graph",
        short: "Seed the search",
        title: "The same query starts from the same entrypoint",
        body: "Both searches prepare the query for PQ-distance comparisons, begin at the graph entrypoint, and seed the beam-search candidate list. AiSAQ keeps the entrypoint PQ code available because no previous hop could have supplied it.",
        summary: "One query, one entrypoint, one candidate-list rule. The first visible difference is only where the entrypoint's compact code is kept ready.",
        sourceLabel: "Paper Algorithm 1 and §3.1 — entrypoint state",
        sourceUrl: `${PAPER_URL}#page=3`,
        duration: 14,
        focus: "entrypoint",
        learningGoal: "See which search state is shared before the first SSD node read.",
        checkpoint: {
          prompt: "Pause: why does AiSAQ retain entrypoint PQ code state even though neighbor codes live in SSD chunks?",
          reveal: "The entrypoint has no previous graph hop from which its code could arrive. The paper therefore keeps the n_ep entrypoint PQ codes in DRAM; n_ep is usually 1.",
          confusionHint: "Every later candidate can be discovered by a previous node, but the first node must be seeded separately.",
        },
        citations: [
          paperSource("§2.3 and Algorithm 1 — beam-search initialization", 2),
          paperSource("§3.1 — entrypoint PQ codes and R + n_ep bound", 3),
        ],
        phases: [
          {
            id: "query-arrives",
            label: "Receive the query",
            shared: "The same query vector enters both systems and will be compared under the dataset's distance metric.",
            diskann: "DiskANN prepares the query for PQ lookup against codes in its DRAM array.",
            aisaq: "AiSAQ prepares the identical query for PQ lookup against codes delivered by node chunks.",
            difference: "The query and distance objective are identical; only the future code source differs.",
            cue: "query-arrival",
            trace: phaseTrace("host", "q ENTERS · q STAYS HOST-SIDE", [
              traceEvent("receive-q", 0, "shared", "Receive query", "host.caller", "host.query", "q (read-only query vector)", "in"),
              traceEvent("prepare-lut", 0.35, "shared", "Prepare common PQ lookup", "host.query + host.pq-centroids", "host.cpu.lut", "query-to-centroid lookup state", "lateral"),
              traceEvent("pin-q", 0.76, "shared", "Pin query residency", "host.query", "host.query", "q remains host-side for PQ and exact-distance math", "stationary"),
            ]),
          },
          {
            id: "seed-entrypoint",
            label: "Seed the entrypoint",
            shared: "Both initialize the candidate list L with the same graph entrypoint s.",
            diskann: "The entrypoint's PQ code is already one member of the all-N DRAM PQ array.",
            aisaq: "The n_ep entrypoint PQ code is retained as small DRAM state because no previous chunk can supply it.",
            difference: "AiSAQ retains a special seed code, not a dataset-wide PQ array.",
            cue: "light-entrypoint",
            trace: phaseTrace("host", "SEED ENTRYPOINT s", [
              traceEvent("diskann-seed-code", 0, "diskann", "Fetch DiskANN seed code", "diskann.dram.pq-array", "diskann.cpu.lut", "PQ code(s)", "lateral"),
              traceEvent("aisaq-seed-code", 0.28, "aisaq", "Fetch AiSAQ seed code", "aisaq.dram.entrypoint", "aisaq.cpu.lut", "n_ep entrypoint PQ code(s)", "lateral"),
              traceEvent("seed-distance", 0.58, "shared", "Score entrypoint", "host.cpu.lut", "host.candidate-list", "ID(s) + scalar PQ distance + unexpanded flag", "out"),
            ]),
          },
          {
            id: "rank-first-candidate",
            label: "Make the first candidate ready",
            shared: "The entrypoint receives a PQ-space distance and becomes the first unexpanded candidate for beam search.",
            diskann: "Its candidate state points into the same graph that DiskANN stored on SSD.",
            aisaq: "Its candidate state points into the same graph that AiSAQ stored on SSD.",
            difference: "No recall or topology difference is introduced at initialization; the split begins at the data fetch for a hop.",
            cue: "seed-candidate-list",
            trace: phaseTrace("host", "L = ID + PQ DISTANCE", [
              traceEvent("rank-seed", 0, "shared", "Order initial candidate", "host.candidate-list", "host.candidate-list", "entrypoint ID + scalar PQ distance + unexpanded flag", "stationary"),
              traceEvent("select-p", 0.42, "shared", "Select unexpanded p", "host.candidate-list", "host.expansion-controller", "node ID p; symbolic teaching candidate", "out", "illustrative"),
              traceEvent("q-still-host", 0.78, "shared", "Keep q available", "host.query", "host.cpu", "read-only input for the coming distance computations", "lateral"),
            ]),
          },
        ],
      },
      {
        id: "read-current-chunk",
        number: 3,
        navLabel: "Read one node",
        short: "Open the current chunk",
        title: "Both read SSD; AiSAQ's chunk brings more of the next hop",
        body: "Beam search chooses a current candidate. On the node-cache miss modeled here, each host issues an aligned logical read for that node's contiguous SSD chunk; 4 KiB units return into reusable DRAM scratch. Both responses contain the current full vector and neighbor IDs. The full-inline AiSAQ response also contains the matching neighbor PQ codes. The query q never travels to SSD.",
        summary: "The cache-miss transport is shared: request down, 4 KiB units up into scratch. DiskANN receives full vector plus IDs; full-inline AiSAQ also receives the PQ bytes needed to score those IDs.",
        sourceLabel: "Paper §2.3, §3.1, Figures 1–2 — node-chunk reads",
        sourceUrl: `${PAPER_URL}#page=4`,
        duration: 16,
        focus: "read",
        learningGoal: "Trace exactly what comes back from SSD on both sides of one graph hop.",
        checkpoint: {
          prompt: "Pause: after the SSD read, what data is common to both chunks, and what extra payload does AiSAQ have?",
          reveal: "Both have the current full vector, outdegree, and neighbor IDs. AiSAQ also has the PQ code corresponding to every neighbor ID.",
          confusionHint: "Look inside the two open chunks before following any pointer to DRAM.",
        },
        citations: [
          paperSource("§2.3 and Figure 1 — DiskANN node chunks", 2),
          paperSource("§3.1 — AiSAQ node-chunk formula and lookup", 3),
          paperSource("Figure 2 — side-by-side chunk contents", 4),
        ],
        phases: [
          {
            id: "choose-current",
            label: "Choose the current node",
            shared: "Beam search selects the top-w closest unexpanded candidates from L; this animation follows one illustrative candidate p.",
            diskann: "DiskANN selects that candidate set using the PQ distances already attached to its list entries.",
            aisaq: "AiSAQ selects the same candidate set under the same graph and search condition.",
            difference: "There is no selection-rule difference; the data-placement difference appears in the read payload.",
            cue: "select-current-node",
            trace: phaseTrace("read", "SELECT p FROM L", [
              traceEvent("read-list-head", 0, "shared", "Inspect candidate list", "host.candidate-list", "host.expansion-controller", "bounded entries: ID + scalar PQ distance + expansion flag", "lateral"),
              traceEvent("choose-symbolic-p", 0.4, "shared", "Choose unexpanded p", "host.expansion-controller", "host.request-queue", "node ID p; no numeric address invented", "out", "illustrative"),
              traceEvent("derive-address", 0.74, "shared", "Resolve symbolic node address", "index.metadata", "host.request-queue", "aligned logical span beginning at LBA(p)", "lateral"),
            ]),
          },
          {
            id: "dispatch-read",
            label: "Read the node chunk",
            shared: "On the node-cache miss shown here, both dispatch an aligned logical SSD read covering the contiguous block span used by the current node chunk.",
            diskann: "The read targets the DiskANN chunk layout for the current node.",
            aisaq: "The read targets the larger AiSAQ chunk layout for the same logical node.",
            difference: "The request travels downward and one or more 4 KiB units return upward into each lane's reusable DRAM scratch. A cache hit would bypass this SSD path.",
            cue: "ssd-read-pulse",
            trace: phaseTrace("read", "CACHE MISS · READ LBA(p)", [
              traceEvent("cache-miss", 0, "shared", "Resolve node-cache miss", "host.node-cache", "host.request-queue", "node p not served by the node cache; cache-hit path is not animated", "lateral"),
              traceEvent("diskann-read-down", 0.18, "diskann", "Issue aligned read", "diskann.host.request-queue", "diskann.ssd.LBA(p)", "aligned logical read for node p at LBA(p)", "down"),
              traceEvent("aisaq-read-down", 0.32, "aisaq", "Issue aligned read", "aisaq.host.request-queue", "aisaq.ssd.LBA(p)", "aligned logical read for node p at LBA(p)", "down"),
              traceEvent("diskann-blocks-up", 0.56, "diskann", "Return DiskANN units", "diskann.ssd.LBA(p)", "diskann.dram.scratch", "4 KiB unit(s): full vector(p) + degree + neighbor IDs", "up"),
              traceEvent("aisaq-blocks-up", 0.72, "aisaq", "Return AiSAQ units", "aisaq.ssd.LBA(p)", "aisaq.dram.scratch", "4 KiB unit(s): full vector(p) + degree + neighbor IDs + inline neighbor PQ codes", "up"),
              traceEvent("q-never-descends", 0.9, "shared", "Keep q host-side", "host.query", "host.query", "q is not part of either storage request", "stationary"),
            ]),
          },
          {
            id: "unpack-common-fields",
            label: "Unpack the common fields",
            shared: "The response exposes the current node's full-precision vector, outdegree r, and r outneighbor IDs.",
            diskann: "DiskANN can now identify which neighbor PQ entries it must consult in DRAM.",
            aisaq: "AiSAQ can now pair each neighbor ID with data located later in the same chunk.",
            difference: "The common prefix has the same meaning, but each ID points to a different physical source for scoring data.",
            cue: "reveal-chunk-prefix",
            trace: phaseTrace("read", "DECODE SCRATCH PREFIX", [
              traceEvent("diskann-prefix", 0, "diskann", "Decode common fields", "diskann.dram.scratch", "diskann.host.decoder", "full vector(p) + outdegree r + r outneighbor IDs", "lateral"),
              traceEvent("aisaq-prefix", 0.34, "aisaq", "Decode common fields", "aisaq.dram.scratch", "aisaq.host.decoder", "full vector(p) + outdegree r + r outneighbor IDs", "lateral"),
              traceEvent("retain-full-for-exact", 0.7, "shared", "Retain current full vector briefly", "diskann.dram.scratch + aisaq.dram.scratch", "scratch.current-vector-field", "full vector(p), pending immediate exact-distance computation", "stationary"),
            ]),
          },
          {
            id: "reveal-neighbor-codes",
            label: "Locate the neighbor codes",
            shared: "Both must obtain one compact PQ code per outgoing neighbor before scoring it.",
            diskann: "Each neighbor ID indexes the dataset-wide PQ array already resident in DRAM.",
            aisaq: "Each neighbor's PQ code is read from the current SSD chunk beside the neighbor-ID list.",
            difference: "DiskANN joins SSD IDs to DRAM codes; AiSAQ completes the join inside the prebuilt SSD chunk.",
            cue: "trace-code-sources",
            trace: phaseTrace("read", "LOCATE NEIGHBOR PQ OPERANDS", [
              traceEvent("diskann-address-pq", 0, "diskann", "Gather by neighbor ID", "diskann.dram.scratch.neighbor-ids", "diskann.dram.pq-array", "addresses of r neighbor PQ codes", "lateral"),
              traceEvent("diskann-pq-to-score", 0.3, "diskann", "Supply global PQ codes", "diskann.dram.pq-array", "diskann.cpu.lut", "r neighbor PQ codes gathered from the all-N array", "lateral"),
              traceEvent("aisaq-pq-to-score", 0.56, "aisaq", "Supply inline PQ codes", "aisaq.dram.scratch.inline-pq", "aisaq.cpu.lut", "r neighbor PQ codes that arrived in scratch", "lateral"),
              traceEvent("common-lut", 0.82, "shared", "Use common centroid lookup", "host.pq-centroids + host.query", "diskann.cpu.lut + aisaq.cpu.lut", "same PQ-distance role; q remains host-side", "lateral"),
            ]),
          },
        ],
      },
      {
        id: "score-neighbors",
        number: 4,
        navLabel: "Score neighbors",
        short: "Compare the routes",
        title: "Same PQ math, different source for its inputs",
        body: "For every outgoing neighbor, both systems estimate distance to the query with that neighbor's PQ code, merge promising IDs into candidate list L, and prune L to its configured limit. AiSAQ can discard hop-local PQ payload after those comparisons.",
        summary: "The distance computation and candidate-list rules stay aligned. DiskANN reads compact codes from DRAM; AiSAQ consumes the compact codes that arrived with the SSD chunk.",
        sourceLabel: "Paper Algorithm 1 and §3.1 — PQ distance computation",
        sourceUrl: `${PAPER_URL}#page=3`,
        duration: 16,
        focus: "score",
        learningGoal: "Separate identical scoring logic from different physical data sources.",
        checkpoint: {
          prompt: "Pause: does AiSAQ change the PQ-distance formula or the graph edges to reduce DRAM?",
          reveal: "No. It changes where the neighbor PQ inputs are stored. The graph topology and PQ-distance role remain the same.",
          confusionHint: "Follow the colored code packets to the same scoring gate on both sides.",
        },
        citations: [
          paperSource("§2.3 and Algorithm 1 — append, merge, and prune L", 2),
          paperSource("§3.1 — distance computation within each node chunk", 3),
          paperSource("Figure 2 — source of neighbor PQ vectors", 4),
        ],
        phases: [
          {
            id: "pair-neighbor-data",
            label: "Pair IDs with PQ codes",
            shared: "Each outgoing neighbor ID is paired with the compact representation used for approximate distance.",
            diskann: "The ID addresses its matching entry in the global DRAM PQ array.",
            aisaq: "The ID aligns with its matching PQ payload in the current SSD node chunk.",
            difference: "The logical pair is identical. DiskANN gathers the code from its global DRAM array by the ID returned from SSD; AiSAQ reads the code that returned in the same scratch payload as that ID.",
            cue: "pair-id-and-code",
            trace: phaseTrace("score", "JOIN ID ↔ PQ CODE", [
              traceEvent("diskann-id-gather", 0, "diskann", "Gather neighbor code", "diskann.dram.scratch.neighbor-ids", "diskann.dram.pq-array", "neighbor ID → matching global PQ-code entry", "lateral"),
              traceEvent("aisaq-inline-pair", 0.38, "aisaq", "Pair inline fields", "aisaq.dram.scratch.neighbor-ids + aisaq.dram.scratch.inline-pq", "aisaq.cpu.lut", "co-located neighbor ID + PQ-code pair", "lateral"),
              traceEvent("pairs-ready", 0.74, "shared", "Present scoring operands", "diskann.dram.pq-array + aisaq.dram.scratch.inline-pq", "diskann.cpu.lut + aisaq.cpu.lut", "r compact codes with their node IDs", "in"),
            ]),
          },
          {
            id: "compute-pq-distance",
            label: "Compute approximate distance",
            shared: "Both compare the query with every neighbor's PQ code using the same compact-distance role.",
            diskann: "Its scoring unit consumes bytes supplied from resident DRAM.",
            aisaq: "Its scoring unit consumes bytes supplied by the just-read SSD chunk.",
            difference: "The computation is shared; the storage tier that supplied its operands differs.",
            cue: "score-neighbor-fanout",
            trace: phaseTrace("score", "COMMON LUT · DIFFERENT CODE SOURCE", [
              traceEvent("read-host-q", 0, "shared", "Read common query state", "host.query + host.pq-centroids", "diskann.cpu.lut + aisaq.cpu.lut", "q and query-to-centroid lookup state; host-local read only", "lateral"),
              traceEvent("diskann-score", 0.28, "diskann", "Compute PQ distances", "diskann.dram.pq-array", "diskann.cpu.lut", "r neighbor PQ codes → r scalar approximate distances", "in"),
              traceEvent("aisaq-score", 0.5, "aisaq", "Compute PQ distances", "aisaq.dram.scratch.inline-pq", "aisaq.cpu.lut", "r neighbor PQ codes → r scalar approximate distances", "in"),
              traceEvent("emit-approx", 0.78, "shared", "Emit approximate scores", "diskann.cpu.lut + aisaq.cpu.lut", "host.candidate-staging", "neighbor IDs + scalar PQ distances", "out"),
            ]),
          },
          {
            id: "update-candidates",
            label: "Merge and prune candidates",
            shared: "A separate seen-ID set rejects duplicate insertions. Promising unseen neighbors enter L with scalar PQ distance and expansion state, then L is pruned to the configured search-list size when necessary.",
            diskann: "DiskANN carries forward neighbor IDs, computed PQ distances, and expansion flags; the seen-ID set remains separate.",
            aisaq: "AiSAQ carries forward the same logical candidate state under the same search setting.",
            difference: "Deduplication, candidate ordering, and expansion state remain comparable; AiSAQ has not purchased memory savings by changing the ranking rule.",
            cue: "update-candidate-queue",
            trace: phaseTrace("score", "SEEN IDs · COMMIT SCALAR STATE TO L", [
              traceEvent("check-seen", 0, "shared", "Check neighbor IDs", "host.candidate-staging", "host.seen-ids", "neighbor IDs checked for prior insertion", "in"),
              traceEvent("mark-unseen", 0.24, "shared", "Mark admitted IDs", "host.seen-ids", "host.seen-ids", "newly admitted neighbor IDs only", "stationary"),
              traceEvent("merge-candidates", 0.46, "shared", "Insert unseen candidates", "host.candidate-staging + host.seen-ids", "host.candidate-list", "ID + scalar PQ distance + unexpanded flag", "in"),
              traceEvent("prune-l", 0.68, "shared", "Prune bounded list", "host.candidate-list", "host.candidate-list", "top-L entries ordered in PQ space", "stationary"),
              traceEvent("l-retention", 0.86, "shared", "Retain traversal state", "host.candidate-list", "host.candidate-list", "ID + scalar PQ distance + expansion flag; no full vector or PQ-code payload", "stationary"),
            ]),
          },
          {
            id: "release-hop-payload",
            label: "Finish with PQ operands",
            shared: "After neighbor scoring, both retain L as IDs, scalar PQ distances, and expansion flags; the seen-ID set remains separate. The current full vector remains in scratch only until its exact distance is computed in the next action.",
            diskann: "Its all-N PQ array remains resident because later IDs may refer to any node.",
            aisaq: "The current hop's inline neighbor PQ bytes need no independent retention after distance computation; they remain merely bytes inside scratch until that buffer is reused.",
            difference: "DiskANN preserves dataset-scale code residency. AiSAQ no longer treats the inline PQ bytes as live operands, but scratch release waits for the current full-vector exact score.",
            cue: "clear-hop-buffer",
            trace: phaseTrace("score", "PQ OPERANDS DEAD · FULL VECTOR STILL LIVE", [
              traceEvent("drop-pq-temporaries", 0, "shared", "End PQ operand lifetime", "diskann.cpu.lut + aisaq.cpu.lut", "host.reusable-temporaries", "temporary gather and LUT outputs; L already owns scalar PQ distances", "release"),
              traceEvent("diskann-array-persists", 0.34, "diskann", "Keep global PQ array resident", "diskann.dram.pq-array", "diskann.dram.pq-array", "all N PQ codes remain addressable for later hops", "stationary"),
              traceEvent("aisaq-inline-dead", 0.58, "aisaq", "Stop referencing inline PQ bytes", "aisaq.dram.scratch.inline-pq", "aisaq.dram.scratch", "inline PQ bytes no longer live as scoring operands", "stationary"),
              traceEvent("full-vector-live", 0.82, "shared", "Hold current full vector", "diskann.dram.scratch + aisaq.dram.scratch", "scratch.current-vector-field", "full vector(p), retained only for immediate exact scoring", "stationary"),
            ]),
          },
        ],
      },
      {
        id: "advance-and-rerank",
        number: 5,
        navLabel: "Advance & re-rank",
        short: "Repeat, then verify",
        title: "Score the full vector now; sort scalar exact scores later",
        body: "During expansion, each system compares q with the current full vector while it is in scratch. The historical authors' implementation writes the node ID and scalar exact distance to an exact-score ledger (full_retset), then releases scratch for reuse. Traversal repeats. At the end, it sorts those retained scalar records and returns the top k; it does not keep a collection of full vectors for a later distance pass. Paper Algorithm 1's V is the logical reranking set and is distinct from the implementation's seen-ID set.",
        summary: "PQ distance and expansion state rank L. Exact distance is computed once when each full vector arrives, an exact-score ledger retains ID plus scalar exact distance, and the final step sorts those scalar records.",
        sourceLabel: "Paper Algorithm 1 and §4.3 — traversal and re-ranking",
        sourceUrl: `${PAPER_URL}#page=2`,
        duration: 16,
        focus: "rerank",
        learningGoal: "Follow the shared loop from approximate navigation through streamed exact scoring to the final exact-score sort.",
        checkpoint: {
          prompt: "Pause: what representation steers the route, and what representation orders the final expanded candidates?",
          reveal: "PQ codes and L's expansion state steer graph navigation. Each expanded node's full vector is scored immediately against q; the implementation's exact-score ledger retains its ID and scalar exact distance for the final sort.",
          confusionHint: "Think compact map while traveling, detailed records at the finish.",
        },
        citations: [
          paperSource("§2.3 and Algorithm 1 — beam-search loop and re-ranking", 2),
          paperSource("§3.1 — AiSAQ hop-local PQ lifecycle", 3),
          paperSource("§4.3 — same topology and recall under the same search condition", 4),
        ],
        phases: [
          {
            id: "record-current-vector",
            label: "Score the current full vector",
            shared: "The CPU compares q with full vector(p) while that vector is in scratch, then appends ID(p) plus the scalar exact distance to the exact-score ledger.",
            diskann: "DiskANN retains the exact-score record, not the full-vector payload.",
            aisaq: "AiSAQ retains the same exact-score record, then can reuse its scratch buffer including the now-dead inline PQ bytes.",
            difference: "No representation difference: both compute exact distance during expansion, retain ID plus scalar exact distance, release scratch, and leave the SSD copy unchanged.",
            cue: "move-current-to-visited",
            trace: phaseTrace("commit", "EXACT SCORE NOW · RETAIN SCALAR", [
              traceEvent("diskann-exact", 0, "diskann", "Compute exact distance", "host.query + diskann.dram.scratch.full-vector(p)", "diskann.cpu.exact", "q × full vector(p) → scalar exact distance", "lateral"),
              traceEvent("aisaq-exact", 0.18, "aisaq", "Compute exact distance", "host.query + aisaq.dram.scratch.full-vector(p)", "aisaq.cpu.exact", "q × full vector(p) → scalar exact distance", "lateral"),
              traceEvent("commit-exact", 0.44, "shared", "Commit exact-score record", "diskann.cpu.exact + aisaq.cpu.exact", "host.exact-score-ledger", "ID(p) + scalar exact distance only", "out"),
              traceEvent("release-scratch", 0.72, "shared", "Release reusable scratch", "diskann.dram.scratch + aisaq.dram.scratch", "host.scratch-pool", "scratch capacity reusable; transported bytes need no retention", "release"),
              traceEvent("ssd-unchanged", 0.9, "shared", "Leave stored copies untouched", "diskann.ssd.LBA(p) + aisaq.ssd.LBA(p)", "storage.at-rest", "prebuilt SSD node chunks remain unchanged", "stationary"),
            ]),
          },
          {
            id: "advance-search",
            label: "Advance along the graph",
            shared: "The next closest unexpanded candidates are selected and the read-score-update cycle repeats until no unexpanded candidates remain in L.",
            diskann: "Each repeated hop combines an SSD node-chunk read with neighbor-code lookups in DRAM.",
            aisaq: "Each repeated hop obtains both neighbor IDs and neighbor PQ codes from that hop's SSD chunk.",
            difference: "The route logic repeats in sync; only the PQ-code supply path keeps diverging.",
            cue: "advance-query-route",
            trace: phaseTrace("commit", "NEXT UNVISITED · REUSE SCRATCH", [
              traceEvent("next-candidate", 0, "shared", "Select next unexpanded candidate", "host.candidate-list", "host.expansion-controller", "ID + scalar PQ distance + expansion flag", "out"),
              traceEvent("repeat-miss-path", 0.45, "shared", "Repeat the modeled hop", "host.request-queue", "diskann.ssd.LBA(p) + aisaq.ssd.LBA(p)", "next symbolic node read on the cache-miss path", "down", "illustrative"),
              traceEvent("reuse-scratch", 0.78, "shared", "Reuse scratch capacity", "host.scratch-pool", "diskann.dram.scratch + aisaq.dram.scratch", "empty reusable buffer capacity", "in"),
            ]),
          },
          {
            id: "rerank-visited",
            label: "Sort retained exact scores",
            shared: "After traversal, both sort the implementation's ID-plus-scalar-exact-distance ledger and choose the top k. This realizes the paper's logical reranking set V without a deferred full-vector distance pass.",
            diskann: "DiskANN already computed each exact distance when its node was expanded.",
            aisaq: "AiSAQ already computed each exact distance at the same expansion point.",
            difference: "This is an exact-score sort, not a deferred pass over retained full-vector payloads.",
            cue: "full-vector-rerank",
            trace: phaseTrace("commit", "SORT EXACT-SCORE LEDGER", [
              traceEvent("sort-exact-ledger", 0, "shared", "Sort exact-score records", "host.exact-score-ledger", "host.exact-sorter", "records: ID + scalar exact distance", "in"),
              traceEvent("take-k", 0.56, "shared", "Select top k", "host.exact-sorter", "host.results", "top-k IDs with scalar exact distances", "out"),
              traceEvent("no-vector-reread", 0.84, "shared", "Avoid a deferred vector pass", "host.scratch-pool", "host.scratch-pool", "no full-vector collection retained for final distance computation", "stationary"),
            ]),
          },
          {
            id: "return-results",
            label: "Return the neighbors",
            shared: "Both return the top-k expanded candidates produced by the shared scalar exact-score sort.",
            diskann: "Under a matched graph and search condition, its result ordering is the baseline comparison.",
            aisaq: "The paper reports identical recall@1 under the same search condition because graph topology is unchanged.",
            difference: "The paper's equivalence claim is scoped to matched conditions; it is not a claim that every latency or deployment property is identical.",
            cue: "deliver-top-k",
            trace: phaseTrace("commit", "RETURN TOP k", [
              traceEvent("return-top-k", 0, "shared", "Return neighbors", "host.results", "host.caller", "top-k node IDs ordered by scalar exact distance", "out"),
              traceEvent("keep-q-host", 0.52, "shared", "End host-side query lifetime", "host.query", "host.query", "q never entered SSD", "stationary"),
              traceEvent("qualify-equivalence", 0.82, "shared", "Scope the comparison", "paper.matched-condition", "reader", "same-recall claim under matched graph and search conditions", "out"),
            ]),
          },
        ],
      },
      {
        id: "block-cost",
        number: 6,
        navLabel: "Count the blocks",
        short: "Price one hop in blocks",
        title: "Fewer DRAM codes can mean a wider SSD read",
        body: "AiSAQ adds R neighbor PQ codes to every node chunk, then storage reads the whole block span containing that chunk. Whether this changes a hop from one 4 KB block to two or four depends on the dataset's vector width, PQ-code size, outdegree, and alignment.",
        summary: "The extra PQ payload is not a separate request, but it can enlarge the node-chunk read. The displayed byte and block examples are derived from the paper's dataset parameters, not universal constants.",
        sourceLabel: "Paper Figure 1, §3.1, Table 1, and §4.3 — block cost",
        sourceUrl: `${PAPER_URL}#page=3`,
        duration: 18,
        focus: "blocks",
        learningGoal: "Derive each side's chunk size and distinguish request count from block-span size.",
        checkpoint: {
          prompt: "Pause: does AiSAQ always read more blocks than DiskANN?",
          reveal: "No. In the site's paper-derived SIFT1B preset, both fit the node read in one 4 KB block. SIFT1M derives one versus two blocks, and KILT E5 22M derives two versus four.",
          confusionHint: "Calculate bytes first, then round each whole chunk up to its occupied 4 KB block span.",
        },
        citations: [
          paperSource("§2.3 and Figure 1 — chunk alignment in LBA blocks", 2),
          paperSource("§3.1 and Table 1 — AiSAQ formula and experimental inputs", 3),
          paperSource("§4.3 — dataset-dependent I/O-size effects", 4),
        ],
        phases: [
          {
            id: "build-chunk-formulas",
            label: "Assemble each chunk",
            shared: "Both begin with b_full bytes for the current full vector and b_num(R + 1) bytes for outdegree plus neighbor IDs.",
            diskann: "Its chunk size is B_DiskANN = b_full + b_num(R + 1).",
            aisaq: "Its chunk adds R·b_PQ bytes, so B_AiSAQ = B_DiskANN + R·b_PQ.",
            difference: "AiSAQ pays one neighbor PQ payload per outgoing edge stored in each prebuilt node chunk.",
            cue: "assemble-chunk-bars",
            trace: phaseTrace("pack", "ASSEMBLE CHUNK BYTES", [
              traceEvent("diskann-formula", 0, "diskann", "Assemble DiskANN bytes", "dataset.preset", "diskann.chunk", "b_full + b_num(R + 1)", "in", "derived"),
              traceEvent("aisaq-formula", 0.48, "aisaq", "Add inline PQ bytes", "dataset.preset", "aisaq.chunk", "B_DiskANN + R·b_PQ", "in", "derived"),
            ]),
          },
          {
            id: "pack-lba-blocks",
            label: "Pack 4 KB blocks",
            shared: "Each chunk occupies a contiguous LBA block span; a chunk that does not fit the previous block's remainder starts at the next block.",
            diskann: "Its smaller chunk can fit one or several records per block, or span multiple blocks for wide full vectors.",
            aisaq: "Its expanded chunk may still fit the same block span or may cross one or more additional block boundaries.",
            difference: "The relevant comparison is ceil(B_chunk / B) for the aligned chunk span, not simply the number of logical fields.",
            cue: "snap-chunks-to-blocks",
            trace: phaseTrace("pack", "SNAP TO 4 KiB UNITS", [
              traceEvent("pack-diskann", 0, "diskann", "Align DiskANN span", "diskann.chunk", "diskann.ssd.LBA(p)", "ceil(B_DiskANN / 4,096) units", "in", "derived"),
              traceEvent("pack-aisaq", 0.5, "aisaq", "Align AiSAQ span", "aisaq.chunk", "aisaq.ssd.LBA(p)", "ceil(B_AiSAQ / 4,096) units", "in", "derived"),
            ]),
          },
          {
            id: "compare-paper-presets",
            label: "Compare the three presets",
            shared: "The lab uses Table 1 dimensions, data types, R values, and PQ-code widths with stated 4-byte and 4 KB teaching assumptions.",
            diskann: "Derived spans are 1 block for SIFT1M, 1 for SIFT1B, and 2 for KILT E5 22M.",
            aisaq: "Derived spans are 2 blocks for SIFT1M, 1 for SIFT1B, and 4 for KILT E5 22M.",
            difference: "Only SIFT1B keeps the same 4 KB span in these presets; these values are dataset-specific derivations, not measured timing points.",
            cue: "cycle-dataset-blocks",
            trace: phaseTrace("pack", "DATASET PRESET DRIVES SPAN", [
              traceEvent("read-preset", 0, "shared", "Read paper inputs", "dataset.selected.paperInputs", "packing.formula", "dimension, type, R, and PQ bytes", "lateral"),
              traceEvent("emit-derived-span", 0.52, "shared", "Emit derived spans", "packing.formula", "diskann.chunk + aisaq.chunk", "dataset-aware chunk bytes, block counts, and I/O bytes", "out", "derived"),
            ]),
          },
          {
            id: "interpret-io-cost",
            label: "Interpret the I/O trade",
            shared: "Both fetch a node chunk from storage for a hop and both benefit from efficient block packing and SSD queueing.",
            diskann: "Its node payload is smaller, while PQ scoring operands remain resident in DRAM.",
            aisaq: "Its PQ operands ride in the node-chunk request, avoiding a separate PQ lookup request but sometimes increasing request size.",
            difference: "The paper reports dataset-dependent latency behavior; the animation's 14–18 second pacing is explanatory and is never query latency.",
            cue: "compare-io-spans",
            trace: phaseTrace("pack", "COMPARE I/O SPAN · NOT LATENCY", [
              traceEvent("compare-spans", 0, "shared", "Compare aligned spans", "diskann.chunk + aisaq.chunk", "reader", "derived 4 KiB unit counts for the selected dataset", "out", "derived"),
              traceEvent("qualify-pacing", 0.58, "shared", "Separate animation time", "simulation.clock", "reader", "phase duration is explanatory, not measured query latency", "out", "illustrative"),
            ]),
          },
        ],
      },
      {
        id: "evidence-switch-limits",
        number: 7,
        navLabel: "Evidence & limits",
        short: "Measure, then qualify",
        title: "The memory and switching wins come with storage and scope limits",
        body: "Tables 2–4 show much smaller measured memory and load or switch times in the authors' setup. Those results accompany a larger AiSAQ SSD index, dataset-dependent query I/O, shared-centroid conditions for the fastest switch, and an evaluated implementation without filtering or dynamic indexing.",
        summary: "Read the exact measurements and their boundaries together: AiSAQ reduces dataset-scale PQ residency and index-loading work, not all process RAM, all SSD cost, or every DiskANN feature.",
        sourceLabel: "Paper §3.2 and §4.2–§4.5 — evidence, switching, and limits",
        sourceUrl: `${PAPER_URL}#page=4`,
        duration: 18,
        focus: "evidence",
        learningGoal: "State the measured wins, principal tradeoff, and evaluation boundaries without overgeneralizing.",
        checkpoint: {
          prompt: "Final pause: what grows, what shrinks, and what must remain qualified?",
          reveal: "Repeated neighbor PQ data grows the SSD index. Dataset-scale DRAM PQ residency and index load or switch work shrink. Query I/O, cost, feature support, and exact timings remain workload- and setup-dependent.",
          confusionHint: "Keep Table 2 memory, Table 3 load time, Table 4 switch time, and §4.5 storage cost as four separate claims.",
        },
        citations: [
          paperSource("§3.2 — evaluated implementation limitations", 3),
          paperSource("Tables 2–4 and §4.2–§4.4", 4),
          paperSource("Figures 5–6, Table 5, and §4.5", 5),
        ],
        phases: [
          {
            id: "memory-and-load-evidence",
            label: "Read memory and load measurements",
            shared: "The paper evaluates both methods with matched index construction and search parameters per dataset in its stated AWS environment.",
            diskann: "Table 2 reports 146, 31,303, and 2,803 MB; Table 3 reports 46.8, 16,437.4, and 1,121.4 ms for SIFT1M, SIFT1B, and KILT E5 22M.",
            aisaq: "Table 2 reports 11, 11, and 14 MB; Table 3 reports 0.6, 0.6, and 2.0 ms for those datasets.",
            difference: "These are measured program-memory and index-load results in the paper's setup, not a promise of literal zero RAM or universal load time.",
            cue: "raise-evidence-bars",
            trace: phaseTrace("evidence", "TABLES 2–3 · MEASURED", [
              traceEvent("load-table-values", 0, "shared", "Load reported values", "paper.tables-2-3", "evidence.panel", "memory MB and index-load ms by dataset", "out"),
              traceEvent("mark-setup", 0.6, "shared", "Attach experiment scope", "paper.section-4", "evidence.panel", "authors' AWS environment and matched parameters", "in"),
            ]),
          },
          {
            id: "switch-evidence",
            label: "Switch KILT subset indices",
            shared: "The switching experiment uses ten KILT E5 2.2M subset indices built with PQ centroids from the full 22M dataset.",
            diskann: "Table 4 reports a 119.2 ms subset-index switch because its search state includes the dataset PQ vectors.",
            aisaq: "Table 4 reports 1.9 ms with centroid reloading and 0.3 ms with shared centroids, where only 4 KB of index metadata is loaded.",
            difference: "The fastest 0.3 ms result depends on compatible indices sharing a PQ centroid codebook; it is not every arbitrary index switch.",
            cue: "switch-index-gates",
            trace: phaseTrace("evidence", "TABLE 4 · SHARED-CENTROID CONDITION", [
              traceEvent("switch-values", 0, "shared", "Compare switch measurements", "paper.table-4", "evidence.switch-panel", "119.2 ms, 1.9 ms, and conditional 0.3 ms", "out"),
              traceEvent("centroid-gate", 0.58, "aisaq", "Gate fastest result", "shared.pq-centroids", "aisaq.index-switch", "compatible shared codebook required", "in"),
            ]),
          },
          {
            id: "storage-latency-cost",
            label: "Balance storage, I/O, and scale",
            shared: "Both still store full vectors and graph structure on storage and both incur node-chunk reads during search.",
            diskann: "It stores N PQ codes once in DRAM for each search process and uses smaller node chunks.",
            aisaq: "It repeats neighbor codes across SSD chunks, approximately R·N·b_PQ bytes by the paper's analysis, and can share that storage across search servers.",
            difference: "AiSAQ is not more cost-effective in the paper's single-server model; its modeled advantage appears with more than two search servers, while query latency remains dataset-dependent.",
            cue: "balance-storage-and-dram",
            trace: phaseTrace("evidence", "SSD GROWS · DATASET PQ DRAM SHRINKS", [
              traceEvent("storage-growth", 0, "aisaq", "Account for repeated PQ", "aisaq.full-inline-layout", "aisaq.ssd.index", "approximately R·N·b_PQ bytes in the paper's analysis", "in"),
              traceEvent("dram-reduction", 0.42, "aisaq", "Remove all-N PQ residency", "aisaq.dram", "evidence.tradeoff", "dataset-scale PQ array absent", "out"),
              traceEvent("cost-scope", 0.76, "shared", "Qualify cost model", "paper.section-4.5", "reader", "server-count and workload dependent", "out"),
            ]),
          },
          {
            id: "implementation-boundaries",
            label: "Mark the boundaries",
            shared: "Both labels in this visual refer to the paper's evaluated DiskANN baseline and AiSAQ implementation, not every possible production variant.",
            diskann: "The baseline retains the full dataset PQ array and provides the established DiskANN feature context.",
            aisaq: "The paper v2 evaluation uses the full-inline layout and reports missing DiskANN additions such as filtering or dynamic indexing. The current authors' repository additionally offers partial or on-demand inline PQ placement, rearrangement, multiple entrypoints, vector beamwidth, and PQ caches.",
            difference: "This visual keeps the paper v2 full-inline cache-miss trace separate from current repository extensions. R + n_ep bounds simultaneous PQ-code state only; other program memory remains.",
            cue: "show-fidelity-boundary",
            trace: phaseTrace("evidence", "SCOPE: v2 FULL-INLINE · CACHE MISS", [
              traceEvent("paper-boundary", 0, "aisaq", "Pin primary visual scope", "paper.v2.full-inline-layout", "simulation.trace", "all neighbor PQ codes inline; evaluated cache-miss transport", "in"),
              traceEvent("cache-hit-disclosure", 0.32, "shared", "Disclose cache-hit branch", "host.node-cache", "reader", "hit bypasses the animated SSD request and return", "out"),
              traceEvent("repo-extension-disclosure", 0.62, "aisaq", "Disclose current repository modes", "authors.current-repository", "reader", "partial/on-demand inline PQ, rearrangement, multiple entrypoints, beamwidth, static/dynamic PQ caches", "out"),
              traceEvent("memory-boundary", 0.86, "aisaq", "Bound the DRAM claim", "paper.table-2", "reader", "R + n_ep is PQ-code state, not total process memory", "out"),
            ]),
          },
        ],
      },
    ],

    benchmarkTables: [
      {
        id: "table-1",
        number: 1,
        title: "Datasets and index build parameters used for AiSAQ experiments",
        columns: ["Dataset", "SIFT1M", "SIFT1B", "KILT E5 22M"],
        rows: [
          ["# of vectors N", "1,000,000", "1,000,000,000", "22,220,792"],
          ["Dimensionality d", "128", "128", "1024"],
          ["Data type", "float", "uint8", "float"],
          ["Distance metric", "Euclid", "Euclid", "MIPS"],
          ["Maximum outdegree R", "56", "52", "69"],
          ["# of PQ subvectors b_PQ", "128", "32", "128"],
        ],
        note: "Each PQ subvector used 256 clusters and one byte, so the subvector count equals the PQ-vector size in bytes for these experiments.",
        source: paperSource("Table 1; §4.1", 3),
      },
      {
        id: "table-2",
        number: 2,
        title: "Memory Usage (MB) by DiskANN and AiSAQ",
        columns: ["Dataset", "b_PQ", "DiskANN", "AiSAQ (ours)"],
        rows: [
          ["SIFT1M", "128 bytes", "146", "11"],
          ["SIFT1B", "32 bytes", "31,303", "11"],
          ["KILT E5 22M", "128 bytes", "2,803", "14"],
        ],
        note: "Peak memory was measured with /usr/bin/time for 10 queries without ground-truth data; both methods otherwise used the same index construction and search parameters for each dataset.",
        source: paperSource("Table 2; §4.2", 4),
      },
      {
        id: "table-3",
        number: 3,
        title: "Index load time (ms) of DiskANN and AiSAQ",
        columns: ["Dataset", "DiskANN", "AiSAQ (ours)"],
        rows: [
          ["SIFT1M", "46.8", "0.6"],
          ["SIFT1B", "16,437.4", "0.6"],
          ["KILT E5 22M", "1,121.4", "2.0"],
        ],
        note: "Single-server experiments used an AWS EC2 i4i.8xlarge with two 3,750 GB instance stores in RAID 0.",
        source: paperSource("Table 3; §4.4", 4),
      },
      {
        id: "table-4",
        number: 4,
        title: "KILT E5 2.2M subset index switch time (ms) of AiSAQ with and without PQ centroids reloading",
        columns: ["Method", "Index switch time (ms)"],
        rows: [
          ["DiskANN", "119.2"],
          ["AiSAQ (PQ centroids reloading)", "1.9"],
          ["AiSAQ (shared PQ centroids)", "0.3"],
        ],
        note: "The authors split KILT E5 22M into 10 subsets built with centroids from the full dataset. With shared centroids, only 4 KB of metadata was loaded for an index.",
        source: paperSource("Table 4; §4.4", 4),
      },
      {
        id: "table-5",
        number: 5,
        title: "DiskANN and AiSAQ comparison with 6 containers search (SIFT1B)",
        columns: ["Metric", "DiskANN", "AiSAQ"],
        rows: [
          ["Total memory usage (MB)", "183,405", "66"],
          ["Average index load time (ms)", "14319.25", "1.7"],
          ["Estimated DRAM & SSD cost (USD)", "344", "103"],
        ],
        note: "The experiment used 3 Lustre storage servers, 6 Docker search containers on one machine, and RDMA over 200 Gb Ethernet. Cost is the paper's estimate under its stated DRAM and SSD price assumptions.",
        source: paperSource("Table 5; §4.5", 5),
      },
    ],

    blockPackingPresets: [
      {
        id: "sift1m",
        label: "SIFT1M",
        description: "A 128-dimensional float vector makes the AiSAQ chunk span two 4 KB blocks.",
        paperInputs: {
          dimensionality: 128,
          dataType: "float",
          maximumOutdegreeR: 56,
          pqVectorBytes: 128,
          inputSource: "Table 1",
        },
        derivationAssumptions: {
          bytesPerFloat: 4,
          bytesPerNodeNumber: 4,
          blockBytes: 4096,
          note: "Derived teaching model: float is treated as 4 bytes; b_num uses the paper's usual 4 bytes; B uses the paper's 4 KB example/default.",
        },
        derived: {
          provenance: "derived",
          fullVectorBytes: { value: 512, formula: "128 × 4 = 512 B" },
          diskannChunkBytes: { value: 740, formula: "512 + 4 × (56 + 1) = 740 B" },
          aisaqChunkBytes: { value: 7908, formula: "740 + 56 × 128 = 7,908 B" },
          diskannBlocksPerNodeRead: { value: 1, formula: "ceil(740 / 4,096) = 1" },
          aisaqBlocksPerNodeRead: { value: 2, formula: "ceil(7,908 / 4,096) = 2" },
          diskannIoBytesPerNodeRead: { value: 4096, formula: "1 × 4,096 = 4,096 B" },
          aisaqIoBytesPerNodeRead: { value: 8192, formula: "2 × 4,096 = 8,192 B" },
          diskannWholeChunksPerBlock: { value: 5, formula: "floor(4,096 / 740) = 5" },
          diskannTailBytesAfterPacking: { value: 396, formula: "4,096 − 5 × 740 = 396 B" },
          aisaqTailBytesInReadSpan: { value: 284, formula: "8,192 − 7,908 = 284 B" },
        },
        sources: [
          paperSource("Table 1 inputs and §3.1 chunk formula", 3),
          paperSource("Figure 1 and §2.3 block rule", 2),
        ],
      },
      {
        id: "sift1b",
        label: "SIFT1B",
        description: "Two 2,004-byte AiSAQ chunks fit in one 4 KB block; one node read remains 4 KB, matching DiskANN's I/O size in the paper.",
        paperInputs: {
          dimensionality: 128,
          dataType: "uint8",
          maximumOutdegreeR: 52,
          pqVectorBytes: 32,
          inputSource: "Table 1",
        },
        derivationAssumptions: {
          bytesPerUint8: 1,
          bytesPerNodeNumber: 4,
          blockBytes: 4096,
          note: "Derived teaching model: uint8 is one byte; b_num uses the paper's usual 4 bytes; B uses the paper's 4 KB example/default.",
        },
        derived: {
          provenance: "derived",
          fullVectorBytes: { value: 128, formula: "128 × 1 = 128 B" },
          diskannChunkBytes: { value: 340, formula: "128 + 4 × (52 + 1) = 340 B" },
          aisaqChunkBytes: { value: 2004, formula: "340 + 52 × 32 = 2,004 B" },
          diskannBlocksPerNodeRead: { value: 1, formula: "ceil(340 / 4,096) = 1" },
          aisaqBlocksPerNodeRead: { value: 1, formula: "ceil(2,004 / 4,096) = 1" },
          diskannIoBytesPerNodeRead: { value: 4096, formula: "1 × 4,096 = 4,096 B" },
          aisaqIoBytesPerNodeRead: { value: 4096, formula: "1 × 4,096 = 4,096 B" },
          diskannWholeChunksPerBlock: { value: 12, formula: "floor(4,096 / 340) = 12" },
          diskannTailBytesAfterPacking: { value: 16, formula: "4,096 − 12 × 340 = 16 B" },
          aisaqWholeChunksPerBlock: { value: 2, formula: "floor(4,096 / 2,004) = 2" },
          aisaqTailBytesAfterPacking: { value: 88, formula: "4,096 − 2 × 2,004 = 88 B" },
        },
        sources: [
          paperSource("Table 1 inputs and §3.1 chunk formula", 3),
          paperSource("§4.3 — equal 4 KB I/O size for SIFT1B", 4),
        ],
      },
      {
        id: "kilt-e5-22m",
        label: "KILT E5 22M",
        description: "The 1,024-dimensional float vector fills one 4 KB block; neighbor metadata makes DiskANN span two blocks, and adding neighbor PQ codes expands AiSAQ to four.",
        paperInputs: {
          dimensionality: 1024,
          dataType: "float",
          maximumOutdegreeR: 69,
          pqVectorBytes: 128,
          inputSource: "Table 1",
        },
        derivationAssumptions: {
          bytesPerFloat: 4,
          bytesPerNodeNumber: 4,
          blockBytes: 4096,
          note: "Derived teaching model: float is treated as 4 bytes; b_num uses the paper's usual 4 bytes; B uses the paper's 4 KB example/default.",
        },
        derived: {
          provenance: "derived",
          fullVectorBytes: { value: 4096, formula: "1,024 × 4 = 4,096 B" },
          diskannChunkBytes: { value: 4376, formula: "4,096 + 4 × (69 + 1) = 4,376 B" },
          aisaqChunkBytes: { value: 13208, formula: "4,376 + 69 × 128 = 13,208 B" },
          diskannBlocksPerNodeRead: { value: 2, formula: "ceil(4,376 / 4,096) = 2" },
          aisaqBlocksPerNodeRead: { value: 4, formula: "ceil(13,208 / 4,096) = 4" },
          diskannIoBytesPerNodeRead: { value: 8192, formula: "2 × 4,096 = 8,192 B" },
          aisaqIoBytesPerNodeRead: { value: 16384, formula: "4 × 4,096 = 16,384 B" },
          diskannTailBytesInReadSpan: { value: 3816, formula: "8,192 − 4,376 = 3,816 B" },
          aisaqTailBytesInReadSpan: { value: 3176, formula: "16,384 − 13,208 = 3,176 B" },
        },
        sources: [
          paperSource("Table 1 inputs and §3.1 chunk formula", 3),
          paperSource("§4.3 — larger AiSAQ I/O for KILT E5 22M", 4),
        ],
      },
    ],

    quiz: [
      {
        id: "q-placement",
        prompt: "What is AiSAQ's defining change relative to DiskANN?",
        options: [
          { id: "a", text: "It replaces the graph with brute-force vector search." },
          { id: "b", text: "It stores each node's outneighbors' PQ codes inside that node's SSD chunk." },
          { id: "c", text: "It removes full-precision vectors and skips re-ranking." },
          { id: "d", text: "It keeps every full-precision vector in DRAM." },
        ],
        answerId: "b",
        explanation: "AiSAQ preserves the graph and re-ranking flow but moves the PQ data needed for the next hop into the current SSD node chunk.",
        source: paperSource("§3.1 and Figure 2", 4),
      },
      {
        id: "q-diskann-hop",
        prompt: "During a DiskANN hop, where do the outneighbor PQ codes come from?",
        options: [
          { id: "a", text: "The dataset-wide PQ array in DRAM." },
          { id: "b", text: "The query file." },
          { id: "c", text: "The current node's full-precision vector." },
          { id: "d", text: "They are regenerated from the neighbor IDs." },
        ],
        answerId: "a",
        explanation: "The SSD chunk supplies neighbor IDs; DiskANN uses those IDs to look up PQ codes retained in DRAM.",
        source: paperSource("§2.3; Algorithm 1; Figure 2", 2),
      },
      {
        id: "q-memory",
        prompt: "What SIFT1B memory values does Table 2 report?",
        options: [
          { id: "a", text: "DiskANN 146 MB; AiSAQ 11 MB" },
          { id: "b", text: "DiskANN 2,803 MB; AiSAQ 14 MB" },
          { id: "c", text: "DiskANN 31,303 MB; AiSAQ 11 MB" },
          { id: "d", text: "DiskANN 183,405 MB; AiSAQ 66 MB" },
        ],
        answerId: "c",
        explanation: "31,303 MB and 11 MB are the single-server SIFT1B values in Table 2. The 183,405 MB and 66 MB pair belongs to the six-container experiment in Table 5.",
        source: paperSource("Table 2", 4),
      },
      {
        id: "q-tradeoff",
        prompt: "Which statement best captures the paper's tradeoff?",
        options: [
          { id: "a", text: "AiSAQ makes every query exact and removes all I/O." },
          { id: "b", text: "AiSAQ uses a larger SSD index to reduce dataset-scale DRAM use and index-load time." },
          { id: "c", text: "AiSAQ is always cheaper than DiskANN on one server." },
          { id: "d", text: "AiSAQ's evaluated implementation adds filtering and dynamic indexing." },
        ],
        answerId: "b",
        explanation: "Neighbor PQ codes are repeated in storage, increasing index size. In return, the full PQ array need not be loaded into DRAM, and reported index-load and switch times are much lower.",
        source: paperSource("§3.2, §4.4, and §4.5", 5),
      },
    ],

    glossary: [
      {
        term: "ANNS",
        expanded: "Approximate Nearest Neighbor Search",
        definition: "A search that quickly returns vectors close to a query without exhaustively comparing every vector.",
      },
      {
        term: "Graph index",
        definition: "A directed graph whose nodes represent dataset vectors and whose edges guide a search toward promising candidates.",
      },
      {
        term: "Vamana",
        definition: "The algorithm DiskANN uses to construct its flat directed graph index.",
      },
      {
        term: "Query vector",
        definition: "The vector representation of the item whose nearest dataset neighbors are requested.",
      },
      {
        term: "Full-precision vector",
        definition: "The detailed vector stored in a node chunk and scored against q while the expanded node is in scratch; only its scalar exact distance is retained.",
      },
      {
        term: "Product quantization (PQ)",
        definition: "A compression method that represents vector subvectors with compact centroid codes for cheaper approximate distance comparisons.",
      },
      {
        term: "PQ vector / PQ code",
        definition: "The sequence of compact subvector codes used to approximate a node vector during graph navigation.",
      },
      {
        term: "PQ centroid",
        definition: "A representative subvector from a PQ codebook. Indices in the same vector space can share the codebook in the paper's switching experiment.",
      },
      {
        term: "Outneighbor",
        definition: "A node reached by following one of the current node's outgoing graph edges.",
      },
      {
        term: "Node chunk",
        definition: "A node's contiguous SSD record. DiskANN stores its full vector, outdegree, and neighbor IDs; AiSAQ also stores those neighbors' PQ codes.",
      },
      {
        term: "Beam search",
        definition: "The graph traversal used here: expand a small set of promising nodes, update a bounded candidate list, and repeat.",
      },
      {
        term: "Candidate list L",
        definition: "The bounded set of promising graph nodes, carrying node ID, scalar PQ distance, and expansion state during traversal.",
      },
      {
        term: "Seen-ID set",
        definition: "A separate deduplication set used to prevent a node ID from being inserted into the candidate search state more than once.",
      },
      {
        term: "Paper V / exact-score ledger",
        definition: "Paper Algorithm 1 uses V as the logical full-precision reranking set. The historical authors' implementation computes exact distance during expansion and stores node ID plus scalar exact distance in full_retset; neither is the C++ seen-ID set.",
      },
      {
        term: "Re-ranking",
        definition: "The final ordering of expanded candidates by scalar exact distances already computed from full vectors during expansion.",
      },
      {
        term: "Recall@1",
        definition: "The fraction of queries for which the true nearest neighbor appears as the first returned result.",
      },
      {
        term: "MIPS",
        expanded: "Maximum Inner Product Search",
        definition: "The distance objective listed for the KILT E5 22M experiment; higher inner product indicates a closer match under that objective.",
      },
      {
        term: "LBA block",
        expanded: "Logical Block Address block",
        definition: "The storage I/O unit used in the paper's layout discussion; the teaching presets use the paper's 4 KB example.",
      },
      {
        term: "Index switch",
        definition: "Changing which prebuilt vector index a search process uses, such as switching a RAG retriever to another corpus.",
      },
    ],

    fidelityNotes: [
      {
        label: "Paper-backed",
        text: "Stage claims and Tables 1–5 are tied to a named section, figure, or table in arXiv:2404.06004v2.",
      },
      {
        label: "Derived",
        text: "Every calculated byte or block value in the packing presets is explicitly marked derived and includes its formula and assumptions.",
      },
      {
        label: "Illustrative",
        text: "Graph positions, colors, the animated visit order, and the number of nodes shown are teaching choices, not coordinates or traces reported by the authors.",
      },
      {
        label: "Plots",
        text: "Figures 3, 4, and 6 support qualitative comparisons only here; the site does not invent point coordinates that the paper does not tabulate.",
      },
    ],

    caveats: [
      {
        id: "not-literally-zero-ram",
        title: "“DRAM-free” does not mean zero process memory",
        text: "AiSAQ removes the dataset-scale all-node PQ array from DRAM. Table 2 still reports 11–14 MB, including program and shared-library memory; §4.2 gives an 11 MB example with 300 KB for the program and static variables and 5.8 MB for shared libraries.",
        source: paperSource("§4.2 and Table 2", 4),
      },
      {
        id: "same-recall-scope",
        title: "Same recall is conditional",
        text: "The paper says recall@1 is identical under the same search condition because graph topology is unchanged. This is not a claim that every configuration, implementation, or workload has identical recall or latency.",
        source: paperSource("§4.3 Query Search Time", 4),
      },
      {
        id: "io-can-grow",
        title: "The SSD read can become larger",
        text: "SIFT1M and KILT E5 22M require more blocks per AiSAQ node chunk than DiskANN in the reported setup. SIFT1B is the favorable case where both read 4 KB.",
        source: paperSource("§4.3 Query Search Time", 4),
      },
      {
        id: "storage-inflation",
        title: "PQ data is repeated in storage",
        text: "The paper models AiSAQ's PQ storage as R·N·b_PQ bytes versus DiskANN's N·b_PQ bytes of DRAM. With R typically around 60, single-server cost is not automatically lower.",
        source: paperSource("§4.5 Cost Analysis", 5),
      },
      {
        id: "benchmark-scope",
        title: "Numbers belong to the authors' experimental setup",
        text: "Tables 2–4 use the paper's AWS instance and index/search settings; Table 5 uses its Lustre, container, CPU, memory, RDMA, and price assumptions. They are not current cloud quotes or an independent reproduction.",
        source: paperSource("§4.1 and §4.5", 5),
      },
      {
        id: "implementation-features",
        title: "The evaluated implementation has missing DiskANN features",
        text: "The authors' memory-first implementation does not support additional DiskANN features such as filtering and dynamic indexing.",
        source: paperSource("§3.2 Implementation", 3),
      },
      {
        id: "packing-assumptions",
        title: "Packing values are transparent derivations",
        text: "The presets infer full-vector bytes from Table 1 by treating float as 4 bytes and uint8 as 1 byte, then use b_num = 4 bytes and B = 4,096 bytes from the paper's usual/example values. Different formats or OS block settings change the result.",
        source: paperSource("§2.3, §3.1, and Table 1", 3),
      },
    ],
  });
})();
