(function () {
  "use strict";

  const PAPER_URL = "https://arxiv.org/pdf/2404.06004";
  const PAPER_ABSTRACT_URL = "https://arxiv.org/abs/2404.06004";

  const paperSource = (label, page) => ({
    label,
    url: `${PAPER_URL}#page=${page}`,
  });

  window.AISAQ_CONTENT = Object.freeze({
    schemaVersion: 1,

    meta: {
      id: "aisaq-visual-guide",
      title: "AiSAQ, one graph hop at a time",
      shortTitle: "Inside AiSAQ",
      subtitle: "See how moving PQ codes from DRAM into SSD node chunks changes memory, I/O, and index switching.",
      paperTitle: "AiSAQ: All-in-Storage ANNS with Product Quantization for DRAM-free Information Retrieval",
      paperVersion: "arXiv:2404.06004v2, 26 February 2025",
      authors: [
        "Kento Tatsuno",
        "Daisuke Miyashita",
        "Taiga Ikeda",
        "Kiyoshi Ishiyama",
        "Kazunari Sumiyoshi",
        "Jun Deguchi",
      ],
      paperUrl: PAPER_URL,
      abstractUrl: PAPER_ABSTRACT_URL,
      estimatedMinutes: 9,
      stageDurationUnit: "seconds",
      learningOutcomes: [
        "Explain which data DiskANN keeps in DRAM and which data it reads from SSD.",
        "Trace one search hop in DiskANN and AiSAQ.",
        "Explain why AiSAQ memory does not grow with the number of indexed vectors in the same way.",
        "Name the SSD-size, I/O, feature, and evaluation caveats behind the headline result.",
      ],
    },

    sources: {
      paper: {
        label: "Primary source: AiSAQ paper, arXiv:2404.06004v2",
        url: PAPER_URL,
      },
      abstract: {
        label: "AiSAQ abstract and version history on arXiv",
        url: PAPER_ABSTRACT_URL,
      },
      learningMethod: {
        label: "Method reference: How I use LLMs to learn complex topics",
        url: "https://laurentiugabriel.github.io/blog/articles/how-i-use-llms-to-learn/",
      },
      implementation: {
        label: "Authors' AiSAQ DiskANN implementation",
        url: "https://github.com/kioxia-jp/aisaq-diskann",
      },
    },

    learningMethod: {
      sourceLabel: "Inspired by Laurentiu Raducu's simulation-based learning workflow",
      sourceUrl: "https://laurentiugabriel.github.io/blog/articles/how-i-use-llms-to-learn/",
      adaptations: [
        "Map abstract concepts to persistent objects: graph nodes, a query marker, DRAM shelves, SSD chunks, and 4 KB blocks.",
        "Let the learner pause, replay, and compare the same graph hop under two data placements.",
        "Follow the walkthrough with retrieval questions instead of relying on rereading alone.",
      ],
    },

    stages: [
      {
        id: "problem",
        number: 1,
        navLabel: "The problem",
        short: "The problem",
        title: "A billion useful shortcuts still occupy memory",
        body: "Graph search avoids scanning every vector, but DiskANN keeps one PQ-compressed code for every node in DRAM so it can score neighbors quickly.",
        sourceLabel: "Paper §2.4 — Drawbacks of DiskANN",
        sourceUrl: `${PAPER_URL}#page=3`,
        duration: 50,
        focus: "overview",
        learningGoal: "Understand why DiskANN's compressed-vector memory still scales with dataset size.",
        summary: "Graph search avoids scanning every vector, but DiskANN keeps one PQ-compressed code for every node in DRAM so it can score neighbors quickly.",
        scene: {
          mode: "scale",
          focus: ["query", "graph", "dram-pq-array", "ssd-index"],
          alt: "A query enters a directed graph. SSD stores node chunks, while a DRAM shelf contains one PQ code for every graph node and grows as nodes are added.",
          beats: [
            "A query vector asks for nearby dataset vectors.",
            "The graph offers a short route instead of a brute-force scan.",
            "DiskANN's DRAM shelf still grows by one PQ code per indexed node.",
          ],
        },
        keyFacts: [
          "Exact nearest-neighbor search by brute force is O(Nd); graph-based ANNS searches approximately.",
          "DiskANN stores PQ-compressed vectors for all N nodes in DRAM.",
          "The paper's example says SIFT1B with 32 bytes per PQ vector requires about 32 GB for those codes.",
        ],
        checkpoint: {
          prompt: "Pause: why can DiskANN's DRAM use grow even when its search visits only a small part of the graph?",
          reveal: "Because the PQ code for every node is resident in DRAM, including nodes that this query never visits.",
          confusionHint: "Separate work done per query from data kept ready for every possible query.",
        },
        citations: [
          paperSource("§2.1 Graph-Based ANNS Algorithms", 2),
          paperSource("§2.4 Drawbacks of DiskANN — Memory Usage and Spatial Efficiency", 3),
        ],
      },
      {
        id: "representations",
        number: 2,
        navLabel: "Two representations",
        short: "Two vector views",
        title: "A compact guide first, an exact check later",
        body: "A compact PQ code helps choose the route through the graph. Full-precision vectors provide the detailed distances used to re-rank the nodes actually visited.",
        sourceLabel: "Paper §2.3 — PQ routing and full-vector re-ranking",
        sourceUrl: `${PAPER_URL}#page=2`,
        duration: 55,
        focus: "pq",
        learningGoal: "Distinguish a full-precision vector from its PQ-compressed representation.",
        summary: "The compressed PQ code is cheap to compare while choosing a route. Full-precision vectors are used later to re-rank the nodes that were actually visited.",
        scene: {
          mode: "representation",
          focus: ["full-vector", "pq-subvectors", "centroid-codes"],
          alt: "One full vector is split into subvectors. Each subvector is represented by a compact centroid code, forming a PQ vector used for approximate comparisons.",
          beats: [
            "Treat the full vector as the detailed record.",
            "Split it into subvectors and encode each with a centroid identifier.",
            "Use PQ distances to steer; use full-precision distances to re-rank visited candidates.",
          ],
        },
        keyFacts: [
          "In the paper's experiments, every PQ subvector is assigned to one of 256 clusters and represented in 8 bits, or 1 byte.",
          "The experimental PQ-code sizes are therefore 128 bytes for SIFT1M, 32 bytes for SIFT1B, and 128 bytes for KILT E5 22M.",
          "Compression helps memory and computation, but more compression can reduce recall even with re-ranking.",
        ],
        checkpoint: {
          prompt: "Pause: which representation chooses promising graph neighbors, and which one performs the final re-ranking?",
          reveal: "PQ codes choose promising neighbors; full-precision vectors re-rank the visited candidates.",
          confusionHint: "Think 'route with the compact map, verify with the detailed record.'",
        },
        citations: [
          paperSource("§2.1 and §2.3; Algorithm 1", 2),
          paperSource("§4.1 Datasets and Experimental Conditions; Table 1", 3),
        ],
      },
      {
        id: "diskann-hop",
        number: 3,
        navLabel: "DiskANN hop",
        short: "Trace DiskANN",
        title: "DiskANN joins one SSD read with a DRAM lookup",
        body: "DiskANN reads the current node's full vector and neighbor IDs from SSD, then follows those IDs into a dataset-wide DRAM array to score the neighbors' PQ codes.",
        sourceLabel: "Paper §2.3 and Algorithm 1 — DiskANN beam search",
        sourceUrl: `${PAPER_URL}#page=2`,
        duration: 75,
        focus: "diskann",
        learningGoal: "Trace where each piece of data comes from during a DiskANN graph hop.",
        summary: "At the current node, DiskANN reads its node chunk from SSD, then uses neighbor IDs from that chunk to find every neighbor's PQ code in the dataset-wide DRAM array.",
        scene: {
          mode: "diskann-hop",
          focus: ["current-node", "ssd-node-chunk", "neighbor-ids", "dram-pq-array", "candidate-list"],
          alt: "DiskANN reads the current node's full vector and neighbor IDs from SSD. Lines from those IDs point to neighbor PQ codes in DRAM, which are scored and added to the candidate list.",
          beats: [
            "Read the current node chunk from SSD: full vector, outdegree, and outneighbor IDs.",
            "Use those IDs to look up the outneighbors' PQ codes in DRAM.",
            "Compare PQ distance, keep the best candidates in list L, and add the current full vector to visited set V.",
            "After traversal, sort visited candidates by full-precision distance and return the top k.",
          ],
        },
        keyFacts: [
          "DiskANN uses a flat directed graph constructed with Vamana.",
          "Algorithm 1 uses beam width w and a candidate list of size L; the paper's evaluation fixes w = 4 and varies L.",
          "The SSD node chunk does not contain the outneighbors' PQ codes in DiskANN's layout.",
        ],
        checkpoint: {
          prompt: "Pause: after DiskANN reads neighbor ID a from SSD, where does it obtain node a's PQ code?",
          reveal: "From the PQ array retained in DRAM.",
          confusionHint: "The SSD chunk supplies the pointer; DRAM supplies the compact vector it points to.",
        },
        citations: [
          paperSource("§2.3 DiskANN; Algorithm 1", 2),
          paperSource("Figure 1 — DiskANN node chunks and block alignment", 2),
          paperSource("Figure 2 — DiskANN data placement, left side", 4),
        ],
      },
      {
        id: "aisaq-hop",
        number: 4,
        navLabel: "AiSAQ hop",
        short: "Trace AiSAQ",
        title: "AiSAQ makes the SSD node chunk self-sufficient for a hop",
        body: "AiSAQ places each outneighbor's PQ code beside its ID in the current node's SSD chunk. One chunk supplies the information needed to score that hop without an all-node PQ array in DRAM.",
        sourceLabel: "Paper Figure 2 — DiskANN and AiSAQ data placement",
        sourceUrl: `${PAPER_URL}#page=4`,
        duration: 75,
        focus: "aisaq",
        learningGoal: "See the single data-placement change that removes the all-node PQ array from DRAM.",
        summary: "AiSAQ appends each outneighbor's PQ code beside its ID in the current node's SSD chunk. The hop can score those neighbors from the chunk it just read.",
        scene: {
          mode: "aisaq-hop",
          focus: ["current-node", "expanded-ssd-node-chunk", "neighbor-pq-codes", "small-dram-state", "candidate-list"],
          alt: "AiSAQ reads an expanded SSD node chunk containing the current full vector, neighbor IDs, and each neighbor's PQ code. The large all-node PQ shelf is absent from DRAM.",
          beats: [
            "Read the expanded node chunk from SSD.",
            "For each outneighbor, find its ID and PQ code together inside that chunk.",
            "Score the neighbor, update the candidate list, then discard the hop's temporary PQ codes.",
            "Keep only entrypoint PQ codes and at most R plus n-ep PQ codes at once, rather than N codes.",
          ],
        },
        keyFacts: [
          "AiSAQ changes data placement, not the graph topology.",
          "PQ codes for a node may be duplicated across chunks whenever that node is an outneighbor.",
          "The paper says the method keeps at most R + n-ep PQ vectors at once; n-ep is 1 in most cases.",
        ],
        checkpoint: {
          prompt: "Pause: what moved, and what did not change?",
          reveal: "The outneighbors' PQ codes moved from a global DRAM array into SSD node chunks. The graph topology did not change.",
          confusionHint: "Compare Figure 2 left and right: the edges are conceptually the same; the compact codes live in a different place.",
        },
        citations: [
          paperSource("§3.1 Methodology", 3),
          paperSource("Figure 2 — DiskANN and AiSAQ data placement", 4),
        ],
      },
      {
        id: "block-packing",
        number: 5,
        navLabel: "Pack the blocks",
        short: "Pack 4 KB blocks",
        title: "Larger chunks are useful only when the blocks cooperate",
        body: "Adding neighbor PQ codes makes AiSAQ chunks larger. Maximum outdegree R is tuned so those chunks use one block, several blocks, or a clean fraction of a block efficiently.",
        sourceLabel: "Paper §3.1 and Table 1 — node-chunk sizing",
        sourceUrl: `${PAPER_URL}#page=3`,
        duration: 70,
        focus: "blocks",
        learningGoal: "Connect node-chunk size to the number of 4 KB blocks read per hop.",
        summary: "Adding neighbor PQ codes makes AiSAQ chunks larger. The maximum outdegree R is tuned so chunks fill one block, several blocks, or a clean fraction of a block with little wasted space.",
        scene: {
          mode: "block-packing",
          focus: ["block-grid", "diskann-chunk", "aisaq-chunk", "unused-space", "preset-selector"],
          alt: "A 4 KB block grid compares DiskANN and AiSAQ node-chunk sizes for three paper datasets. Every calculated byte and block count is marked derived.",
          beats: [
            "Start with a full vector, an outdegree field, and R neighbor IDs.",
            "For AiSAQ, add R neighbor PQ codes.",
            "Round each read up to whole 4 KB blocks.",
            "Switch presets to see why SIFT1B keeps a 4 KB read while SIFT1M and KILT E5 use more blocks.",
          ],
        },
        formulas: [
          "B_DiskANN = b_full + b_num(R + 1)",
          "B_AiSAQ = B_DiskANN + R·b_PQ",
          "blocks read per node chunk = ceil(B_chunk / B)",
        ],
        presetIds: ["sift1m", "sift1b", "kilt-e5-22m"],
        checkpoint: {
          prompt: "Pause: does placing PQ codes on SSD always require a separate PQ-code I/O request?",
          reveal: "No. The codes ride inside the node chunk. The chunk may require more blocks, but there is no separate lookup request just for PQ codes.",
          confusionHint: "Count blocks for the whole expanded chunk, not one request for IDs plus another request for PQ codes.",
        },
        citations: [
          paperSource("Figure 1 and §2.3 — node chunks in LBA blocks", 2),
          paperSource("§3.1 Methodology; Table 1 inputs", 3),
          paperSource("§4.3 Query Search Time; Figures 3 and 4", 4),
        ],
      },
      {
        id: "evidence",
        number: 6,
        navLabel: "Evidence",
        short: "Read the results",
        title: "The measured win is memory and load time",
        body: "In the authors' matched experiments, AiSAQ used 11–14 MB in Table 2 and loaded indices in 0.6–2.0 ms in Table 3. Treat these as scoped measurements, not universal guarantees.",
        sourceLabel: "Paper Tables 2–3 — memory and index-load results",
        sourceUrl: `${PAPER_URL}#page=4`,
        duration: 65,
        focus: "evidence",
        learningGoal: "Read the paper's benchmark tables without turning them into universal guarantees.",
        summary: "Under the paper's matched search conditions, AiSAQ used 11–14 MB in Table 2 and loaded indices in 0.6–2.0 ms in Table 3. DiskANN's corresponding values grew sharply with dataset size.",
        scene: {
          mode: "evidence",
          focus: ["dataset-selector", "memory-bars", "load-time-bars", "scope-note"],
          alt: "Exact values from Tables 2 and 3 compare memory use and index load time for SIFT1M, SIFT1B, and KILT E5 22M.",
          beats: [
            "Select one of the three datasets.",
            "Compare the exact Table 2 memory values.",
            "Compare the exact Table 3 index-load values.",
            "Read the experimental-scope note before generalizing.",
          ],
        },
        tableIds: ["table-2", "table-3"],
        keyFacts: [
          "SIFT1B memory: DiskANN 31,303 MB; AiSAQ 11 MB.",
          "SIFT1B index load: DiskANN 16,437.4 ms; AiSAQ 0.6 ms.",
          "For the same search condition, recall@1 is identical because AiSAQ does not change graph topology; latency can differ because chunk I/O size can differ.",
        ],
        checkpoint: {
          prompt: "Pause: what does Table 2 report for SIFT1B?",
          reveal: "31,303 MB for DiskANN and 11 MB for AiSAQ.",
          confusionHint: "These are measured program memory values in the paper's setup, not only a calculation of raw PQ bytes.",
        },
        citations: [
          paperSource("§4.1 Experimental Conditions", 3),
          paperSource("Table 2 and §4.2 Memory Usage", 4),
          paperSource("Table 3 and §4.4 Index Switch", 4),
        ],
      },
      {
        id: "tradeoffs-switching",
        number: 7,
        navLabel: "Tradeoffs & switching",
        short: "Tradeoffs",
        title: "Spend SSD space to free DRAM—and switch indices quickly",
        body: "AiSAQ repeats neighbor PQ data in storage, inflating the SSD index, but avoids loading a dataset-wide PQ array. That enables the paper's fast index-switch results and can benefit shared-storage, multi-server search.",
        sourceLabel: "Paper §4.5 and Table 5 — multi-server cost tradeoff",
        sourceUrl: `${PAPER_URL}#page=5`,
        duration: 70,
        focus: "tradeoffs",
        learningGoal: "State AiSAQ's principal tradeoff and the conditions behind its switching and cost claims.",
        summary: "AiSAQ repeats neighbor PQ data in storage, inflating the SSD index, but avoids loading a dataset-wide PQ array. That makes index switching fast and can help when several search servers share storage.",
        scene: {
          mode: "tradeoffs",
          focus: ["ssd-growth", "index-switch", "shared-centroids", "server-scale", "caveat-card"],
          alt: "A balance compares larger shared SSD storage with much smaller per-search-process DRAM. An index switch reuses shared PQ centroids and loads small metadata.",
          beats: [
            "See PQ codes repeated along graph edges in the SSD index.",
            "Switch from one KILT subset index to another.",
            "Reuse shared PQ centroids so only 4 KB of index metadata needs loading in the paper's experiment.",
            "Scale to six search containers and compare the exact Table 5 totals.",
          ],
        },
        tableIds: ["table-4", "table-5"],
        keyFacts: [
          "Table 4 reports 119.2 ms for DiskANN, 1.9 ms for AiSAQ with centroid reloading, and 0.3 ms for AiSAQ with shared centroids on KILT E5 2.2M subset indices.",
          "The paper estimates AiSAQ is not more cost-effective on one server under its price assumptions; the modeled advantage appears with more than two search servers.",
          "The evaluated implementation does not support DiskANN features such as filtering and dynamic indexing.",
        ],
        checkpoint: {
          prompt: "Final pause: what is the trade—what grows, what shrinks, and what becomes faster to switch?",
          reveal: "The SSD index grows because neighbor PQ codes are repeated. Dataset-scale DRAM residency shrinks, and indices can be loaded or switched much faster in the reported setup.",
          confusionHint: "AiSAQ is a placement trade, not free compression: storage takes on work that DRAM used to do.",
        },
        citations: [
          paperSource("§3.2 Implementation limitations", 3),
          paperSource("Table 4 and §4.4 Index Switch", 4),
          paperSource("Figures 5–6, Table 5, and §4.5 Cost Analysis", 5),
        ],
      },
    ],

    benchmarkTables: [
      {
        id: "table-1",
        number: 1,
        title: "Datasets and index build parameters used for AiSAQ experiments",
        columns: ["Dataset", "SIFT1M", "SIFT1B", "KILT E5 22M"],
        rows: [
          ["# of vectors N", "1,000,000", "1,000,000,000", "22,220,792"],
          ["Dimensionality d", "128", "128", "1024"],
          ["Data type", "float", "uint8", "float"],
          ["Distance metric", "Euclid", "Euclid", "MIPS"],
          ["Maximum outdegree R", "56", "52", "69"],
          ["# of PQ subvectors b_PQ", "128", "32", "128"],
        ],
        note: "Each PQ subvector used 256 clusters and one byte, so the subvector count equals the PQ-vector size in bytes for these experiments.",
        source: paperSource("Table 1; §4.1", 3),
      },
      {
        id: "table-2",
        number: 2,
        title: "Memory Usage (MB) by DiskANN and AiSAQ",
        columns: ["Dataset", "b_PQ", "DiskANN", "AiSAQ (ours)"],
        rows: [
          ["SIFT1M", "128 bytes", "146", "11"],
          ["SIFT1B", "32 bytes", "31,303", "11"],
          ["KILT E5 22M", "128 bytes", "2,803", "14"],
        ],
        note: "Peak memory was measured with /usr/bin/time for 10 queries without ground-truth data; both methods otherwise used the same index construction and search parameters for each dataset.",
        source: paperSource("Table 2; §4.2", 4),
      },
      {
        id: "table-3",
        number: 3,
        title: "Index load time (ms) of DiskANN and AiSAQ",
        columns: ["Dataset", "DiskANN", "AiSAQ (ours)"],
        rows: [
          ["SIFT1M", "46.8", "0.6"],
          ["SIFT1B", "16,437.4", "0.6"],
          ["KILT E5 22M", "1,121.4", "2.0"],
        ],
        note: "Single-server experiments used an AWS EC2 i4i.8xlarge with two 3,750 GB instance stores in RAID 0.",
        source: paperSource("Table 3; §4.4", 4),
      },
      {
        id: "table-4",
        number: 4,
        title: "KILT E5 2.2M subset index switch time (ms) of AiSAQ with and without PQ centroids reloading",
        columns: ["Method", "Index switch time (ms)"],
        rows: [
          ["DiskANN", "119.2"],
          ["AiSAQ (PQ centroids reloading)", "1.9"],
          ["AiSAQ (shared PQ centroids)", "0.3"],
        ],
        note: "The authors split KILT E5 22M into 10 subsets built with centroids from the full dataset. With shared centroids, only 4 KB of metadata was loaded for an index.",
        source: paperSource("Table 4; §4.4", 4),
      },
      {
        id: "table-5",
        number: 5,
        title: "DiskANN and AiSAQ comparison with 6 containers search (SIFT1B)",
        columns: ["Metric", "DiskANN", "AiSAQ"],
        rows: [
          ["Total memory usage (MB)", "183,405", "66"],
          ["Average index load time (ms)", "14319.25", "1.7"],
          ["Estimated DRAM & SSD cost (USD)", "344", "103"],
        ],
        note: "The experiment used 3 Lustre storage servers, 6 Docker search containers on one machine, and RDMA over 200 Gb Ethernet. Cost is the paper's estimate under its stated DRAM and SSD price assumptions.",
        source: paperSource("Table 5; §4.5", 5),
      },
    ],

    blockPackingPresets: [
      {
        id: "sift1m",
        label: "SIFT1M",
        description: "A 128-dimensional float vector makes the AiSAQ chunk span two 4 KB blocks.",
        paperInputs: {
          dimensionality: 128,
          dataType: "float",
          maximumOutdegreeR: 56,
          pqVectorBytes: 128,
          inputSource: "Table 1",
        },
        derivationAssumptions: {
          bytesPerFloat: 4,
          bytesPerNodeNumber: 4,
          blockBytes: 4096,
          note: "Derived teaching model: float is treated as 4 bytes; b_num uses the paper's usual 4 bytes; B uses the paper's 4 KB example/default.",
        },
        derived: {
          provenance: "derived",
          fullVectorBytes: { value: 512, formula: "128 × 4 = 512 B" },
          diskannChunkBytes: { value: 740, formula: "512 + 4 × (56 + 1) = 740 B" },
          aisaqChunkBytes: { value: 7908, formula: "740 + 56 × 128 = 7,908 B" },
          diskannBlocksPerNodeRead: { value: 1, formula: "ceil(740 / 4,096) = 1" },
          aisaqBlocksPerNodeRead: { value: 2, formula: "ceil(7,908 / 4,096) = 2" },
          diskannIoBytesPerNodeRead: { value: 4096, formula: "1 × 4,096 = 4,096 B" },
          aisaqIoBytesPerNodeRead: { value: 8192, formula: "2 × 4,096 = 8,192 B" },
          diskannWholeChunksPerBlock: { value: 5, formula: "floor(4,096 / 740) = 5" },
          diskannTailBytesAfterPacking: { value: 396, formula: "4,096 − 5 × 740 = 396 B" },
          aisaqTailBytesInReadSpan: { value: 284, formula: "8,192 − 7,908 = 284 B" },
        },
        sources: [
          paperSource("Table 1 inputs and §3.1 chunk formula", 3),
          paperSource("Figure 1 and §2.3 block rule", 2),
        ],
      },
      {
        id: "sift1b",
        label: "SIFT1B",
        description: "Two 2,004-byte AiSAQ chunks fit in one 4 KB block; one node read remains 4 KB, matching DiskANN's I/O size in the paper.",
        paperInputs: {
          dimensionality: 128,
          dataType: "uint8",
          maximumOutdegreeR: 52,
          pqVectorBytes: 32,
          inputSource: "Table 1",
        },
        derivationAssumptions: {
          bytesPerUint8: 1,
          bytesPerNodeNumber: 4,
          blockBytes: 4096,
          note: "Derived teaching model: uint8 is one byte; b_num uses the paper's usual 4 bytes; B uses the paper's 4 KB example/default.",
        },
        derived: {
          provenance: "derived",
          fullVectorBytes: { value: 128, formula: "128 × 1 = 128 B" },
          diskannChunkBytes: { value: 340, formula: "128 + 4 × (52 + 1) = 340 B" },
          aisaqChunkBytes: { value: 2004, formula: "340 + 52 × 32 = 2,004 B" },
          diskannBlocksPerNodeRead: { value: 1, formula: "ceil(340 / 4,096) = 1" },
          aisaqBlocksPerNodeRead: { value: 1, formula: "ceil(2,004 / 4,096) = 1" },
          diskannIoBytesPerNodeRead: { value: 4096, formula: "1 × 4,096 = 4,096 B" },
          aisaqIoBytesPerNodeRead: { value: 4096, formula: "1 × 4,096 = 4,096 B" },
          diskannWholeChunksPerBlock: { value: 12, formula: "floor(4,096 / 340) = 12" },
          diskannTailBytesAfterPacking: { value: 16, formula: "4,096 − 12 × 340 = 16 B" },
          aisaqWholeChunksPerBlock: { value: 2, formula: "floor(4,096 / 2,004) = 2" },
          aisaqTailBytesAfterPacking: { value: 88, formula: "4,096 − 2 × 2,004 = 88 B" },
        },
        sources: [
          paperSource("Table 1 inputs and §3.1 chunk formula", 3),
          paperSource("§4.3 — equal 4 KB I/O size for SIFT1B", 4),
        ],
      },
      {
        id: "kilt-e5-22m",
        label: "KILT E5 22M",
        description: "The 1,024-dimensional float vector fills one 4 KB block; neighbor metadata makes DiskANN span two blocks, and adding neighbor PQ codes expands AiSAQ to four.",
        paperInputs: {
          dimensionality: 1024,
          dataType: "float",
          maximumOutdegreeR: 69,
          pqVectorBytes: 128,
          inputSource: "Table 1",
        },
        derivationAssumptions: {
          bytesPerFloat: 4,
          bytesPerNodeNumber: 4,
          blockBytes: 4096,
          note: "Derived teaching model: float is treated as 4 bytes; b_num uses the paper's usual 4 bytes; B uses the paper's 4 KB example/default.",
        },
        derived: {
          provenance: "derived",
          fullVectorBytes: { value: 4096, formula: "1,024 × 4 = 4,096 B" },
          diskannChunkBytes: { value: 4376, formula: "4,096 + 4 × (69 + 1) = 4,376 B" },
          aisaqChunkBytes: { value: 13208, formula: "4,376 + 69 × 128 = 13,208 B" },
          diskannBlocksPerNodeRead: { value: 2, formula: "ceil(4,376 / 4,096) = 2" },
          aisaqBlocksPerNodeRead: { value: 4, formula: "ceil(13,208 / 4,096) = 4" },
          diskannIoBytesPerNodeRead: { value: 8192, formula: "2 × 4,096 = 8,192 B" },
          aisaqIoBytesPerNodeRead: { value: 16384, formula: "4 × 4,096 = 16,384 B" },
          diskannTailBytesInReadSpan: { value: 3816, formula: "8,192 − 4,376 = 3,816 B" },
          aisaqTailBytesInReadSpan: { value: 3176, formula: "16,384 − 13,208 = 3,176 B" },
        },
        sources: [
          paperSource("Table 1 inputs and §3.1 chunk formula", 3),
          paperSource("§4.3 — larger AiSAQ I/O for KILT E5 22M", 4),
        ],
      },
    ],

    quiz: [
      {
        id: "q-placement",
        prompt: "What is AiSAQ's defining change relative to DiskANN?",
        options: [
          { id: "a", text: "It replaces the graph with brute-force vector search." },
          { id: "b", text: "It stores each node's outneighbors' PQ codes inside that node's SSD chunk." },
          { id: "c", text: "It removes full-precision vectors and skips re-ranking." },
          { id: "d", text: "It keeps every full-precision vector in DRAM." },
        ],
        answerId: "b",
        explanation: "AiSAQ preserves the graph and re-ranking flow but moves the PQ data needed for the next hop into the current SSD node chunk.",
        source: paperSource("§3.1 and Figure 2", 4),
      },
      {
        id: "q-diskann-hop",
        prompt: "During a DiskANN hop, where do the outneighbor PQ codes come from?",
        options: [
          { id: "a", text: "The dataset-wide PQ array in DRAM." },
          { id: "b", text: "The query file." },
          { id: "c", text: "The current node's full-precision vector." },
          { id: "d", text: "They are regenerated from the neighbor IDs." },
        ],
        answerId: "a",
        explanation: "The SSD chunk supplies neighbor IDs; DiskANN uses those IDs to look up PQ codes retained in DRAM.",
        source: paperSource("§2.3; Algorithm 1; Figure 2", 2),
      },
      {
        id: "q-memory",
        prompt: "What SIFT1B memory values does Table 2 report?",
        options: [
          { id: "a", text: "DiskANN 146 MB; AiSAQ 11 MB" },
          { id: "b", text: "DiskANN 2,803 MB; AiSAQ 14 MB" },
          { id: "c", text: "DiskANN 31,303 MB; AiSAQ 11 MB" },
          { id: "d", text: "DiskANN 183,405 MB; AiSAQ 66 MB" },
        ],
        answerId: "c",
        explanation: "31,303 MB and 11 MB are the single-server SIFT1B values in Table 2. The 183,405 MB and 66 MB pair belongs to the six-container experiment in Table 5.",
        source: paperSource("Table 2", 4),
      },
      {
        id: "q-tradeoff",
        prompt: "Which statement best captures the paper's tradeoff?",
        options: [
          { id: "a", text: "AiSAQ makes every query exact and removes all I/O." },
          { id: "b", text: "AiSAQ uses a larger SSD index to reduce dataset-scale DRAM use and index-load time." },
          { id: "c", text: "AiSAQ is always cheaper than DiskANN on one server." },
          { id: "d", text: "AiSAQ's evaluated implementation adds filtering and dynamic indexing." },
        ],
        answerId: "b",
        explanation: "Neighbor PQ codes are repeated in storage, increasing index size. In return, the full PQ array need not be loaded into DRAM, and reported index-load and switch times are much lower.",
        source: paperSource("§3.2, §4.4, and §4.5", 5),
      },
    ],

    glossary: [
      {
        term: "ANNS",
        expanded: "Approximate Nearest Neighbor Search",
        definition: "A search that quickly returns vectors close to a query without exhaustively comparing every vector.",
      },
      {
        term: "Graph index",
        definition: "A directed graph whose nodes represent dataset vectors and whose edges guide a search toward promising candidates.",
      },
      {
        term: "Vamana",
        definition: "The algorithm DiskANN uses to construct its flat directed graph index.",
      },
      {
        term: "Query vector",
        definition: "The vector representation of the item whose nearest dataset neighbors are requested.",
      },
      {
        term: "Full-precision vector",
        definition: "The detailed vector stored in a node chunk and used to re-rank visited candidates by full-precision distance.",
      },
      {
        term: "Product quantization (PQ)",
        definition: "A compression method that represents vector subvectors with compact centroid codes for cheaper approximate distance comparisons.",
      },
      {
        term: "PQ vector / PQ code",
        definition: "The sequence of compact subvector codes used to approximate a node vector during graph navigation.",
      },
      {
        term: "PQ centroid",
        definition: "A representative subvector from a PQ codebook. Indices in the same vector space can share the codebook in the paper's switching experiment.",
      },
      {
        term: "Outneighbor",
        definition: "A node reached by following one of the current node's outgoing graph edges.",
      },
      {
        term: "Node chunk",
        definition: "A node's contiguous SSD record. DiskANN stores its full vector, outdegree, and neighbor IDs; AiSAQ also stores those neighbors' PQ codes.",
      },
      {
        term: "Beam search",
        definition: "The graph traversal used here: expand a small set of promising nodes, update a bounded candidate list, and repeat.",
      },
      {
        term: "Candidate list L",
        definition: "The bounded set of promising graph nodes ranked using PQ-space distance during traversal.",
      },
      {
        term: "Visited set V",
        definition: "The searched nodes whose full-precision vectors are available for final re-ranking.",
      },
      {
        term: "Re-ranking",
        definition: "Sorting visited candidates using full-precision distance after graph traversal.",
      },
      {
        term: "Recall@1",
        definition: "The fraction of queries for which the true nearest neighbor appears as the first returned result.",
      },
      {
        term: "MIPS",
        expanded: "Maximum Inner Product Search",
        definition: "The distance objective listed for the KILT E5 22M experiment; higher inner product indicates a closer match under that objective.",
      },
      {
        term: "LBA block",
        expanded: "Logical Block Address block",
        definition: "The storage I/O unit used in the paper's layout discussion; the teaching presets use the paper's 4 KB example.",
      },
      {
        term: "Index switch",
        definition: "Changing which prebuilt vector index a search process uses, such as switching a RAG retriever to another corpus.",
      },
    ],

    fidelityNotes: [
      {
        label: "Paper-backed",
        text: "Stage claims and Tables 1–5 are tied to a named section, figure, or table in arXiv:2404.06004v2.",
      },
      {
        label: "Derived",
        text: "Every calculated byte or block value in the packing presets is explicitly marked derived and includes its formula and assumptions.",
      },
      {
        label: "Illustrative",
        text: "Graph positions, colors, the animated visit order, and the number of nodes shown are teaching choices, not coordinates or traces reported by the authors.",
      },
      {
        label: "Plots",
        text: "Figures 3, 4, and 6 support qualitative comparisons only here; the site does not invent point coordinates that the paper does not tabulate.",
      },
    ],

    caveats: [
      {
        id: "not-literally-zero-ram",
        title: "“DRAM-free” does not mean zero process memory",
        text: "AiSAQ removes the dataset-scale all-node PQ array from DRAM. Table 2 still reports 11–14 MB, including program and shared-library memory; §4.2 gives an 11 MB example with 300 KB for the program and static variables and 5.8 MB for shared libraries.",
        source: paperSource("§4.2 and Table 2", 4),
      },
      {
        id: "same-recall-scope",
        title: "Same recall is conditional",
        text: "The paper says recall@1 is identical under the same search condition because graph topology is unchanged. This is not a claim that every configuration, implementation, or workload has identical recall or latency.",
        source: paperSource("§4.3 Query Search Time", 4),
      },
      {
        id: "io-can-grow",
        title: "The SSD read can become larger",
        text: "SIFT1M and KILT E5 22M require more blocks per AiSAQ node chunk than DiskANN in the reported setup. SIFT1B is the favorable case where both read 4 KB.",
        source: paperSource("§4.3 Query Search Time", 4),
      },
      {
        id: "storage-inflation",
        title: "PQ data is repeated in storage",
        text: "The paper models AiSAQ's PQ storage as R·N·b_PQ bytes versus DiskANN's N·b_PQ bytes of DRAM. With R typically around 60, single-server cost is not automatically lower.",
        source: paperSource("§4.5 Cost Analysis", 5),
      },
      {
        id: "benchmark-scope",
        title: "Numbers belong to the authors' experimental setup",
        text: "Tables 2–4 use the paper's AWS instance and index/search settings; Table 5 uses its Lustre, container, CPU, memory, RDMA, and price assumptions. They are not current cloud quotes or an independent reproduction.",
        source: paperSource("§4.1 and §4.5", 5),
      },
      {
        id: "implementation-features",
        title: "The evaluated implementation has missing DiskANN features",
        text: "The authors' memory-first implementation does not support additional DiskANN features such as filtering and dynamic indexing.",
        source: paperSource("§3.2 Implementation", 3),
      },
      {
        id: "packing-assumptions",
        title: "Packing values are transparent derivations",
        text: "The presets infer full-vector bytes from Table 1 by treating float as 4 bytes and uint8 as 1 byte, then use b_num = 4 bytes and B = 4,096 bytes from the paper's usual/example values. Different formats or OS block settings change the result.",
        source: paperSource("§2.3, §3.1, and Table 1", 3),
      },
    ],
  });
})();
